package com.kasite.core.serviceinterface.module.order.req;/** * @author linjianfa * @Description: API，订单扩展API * @version: V1.0   * 2017-7-4 下午8:27:57 */import com.alibaba.fastjson.JSONObject;public class ReqOrderExtension extends JSONObject{		/**	 * 	 */	private static final long serialVersionUID = -7844348966840701235L;	public enum PrescriptionOrderMemoEnum {		DoctorCode,		DoctorName,		DeptCode,		DeptName,		;	}	public enum SettleOrderSettlementEnum{		HisOrderId,		PrescNos,		DoctorName,		DeptName,		;	}		public ReqOrderExtension() {	}	public ReqOrderExtension addPrescriptionOrderMemo(PrescriptionOrderMemoEnum memoEnum,String value) {		put(memoEnum.name(), value);		return this;	}		public ReqOrderExtension addSettleOrderSettlementMemo(SettleOrderSettlementEnum memoEnum,String value) {		put(memoEnum.name(), value);		return this;	}		//	private String deviceId;//	private String model;//	private String orderId;  
//
//	private String doctorCode;  
//
//	private String doctorName;  
//
//	private String deptCode;  
//
//	private String deptName; //	//	private String doctorTitle;//	
//	public String getDoctorTitle() {//		return doctorTitle;//	}////	public void setDoctorTitle(String doctorTitle) {//		this.doctorTitle = doctorTitle;//	}////	/**扩展字段*/
//	private String extension;//	
//	public String getOrderId() {//		return orderId;//	}////	public void setOrderId(String orderId) {//		this.orderId = orderId;//	}////	public String getDoctorName() {//		return doctorName;//	}////	public void setDoctorName(String doctorName) {//		this.doctorName = doctorName;//	}////	public String getDeptName() {//		return deptName;//	}////	public void setDeptName(String deptName) {//		this.deptName = deptName;//	}//	//	public String getDoctorCode() {//		return doctorCode;//	}////	public void setDoctorCode(String doctorCode) {//		this.doctorCode = doctorCode;//	}////	public String getDeptCode() {//		return deptCode;//	}////	public void setDeptCode(String deptCode) {//		this.deptCode = deptCode;//	}////	public String getExtension() {//		return extension;//	}////	public void setExtension(String extension) {//		this.extension = extension;//	}////	public String getDeviceId() {//		return deviceId;//	}////	public void setDeviceId(String deviceId) {//		this.deviceId = deviceId;//	}////	public String getModel() {//		return model;//	}////	public void setModel(String model) {//		this.model = model;//	}////	public ReqOrderExtension() {//	}//	//	public ReqOrderExtension(Element data) throws AbsHosException {//		init(data);//	}//	public ReqOrderExtension init(Element data) throws AbsHosException {//		this.doctorCode = XMLUtil.getString(data, "DoctorCode", false);//		this.doctorName = XMLUtil.getString(data, "DoctorName", false);//		this.deptCode = XMLUtil.getString(data, "DeptCode", false);//		this.deptName = XMLUtil.getString(data, "DeptName", false);//		this.doctorTitle = XMLUtil.getString(data, "DoctorTitle", false);//		this.extension = XMLUtil.getString(data, "Extension", false);//		this.deviceId = XMLUtil.getString(data, "DeviceId", false);//		this.model = XMLUtil.getString(data, "Model", false);//		return this;//	}//	//	public ReqOrderExtension(String paramXml) throws DocumentException, AbsHosException {//		Element root = DocumentHelper.parseText(paramXml).getRootElement();//		init(root);//	}//	//	public OrderExtension toOrderExtension(String orderId){//		OrderExtension orderExtension = new OrderExtension();//		if(!StringUtil.isBlank(orderId)){//			orderExtension.setOrderId(orderId);//		}//		orderExtension.setDeptName(deptName);//		orderExtension.setDoctorCode(doctorCode);//		orderExtension.setDoctorName(doctorName);//		orderExtension.setDeptCode(deptCode);//		orderExtension.setExtendField1(extension);//		return orderExtension;//	}

}