package com.kasite.client.core.msg.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.kasite.client.core.msg.bean.dbo.MsgQueue;
import com.kasite.core.serviceinterface.module.msg.req.ReqMsgQueueList;
import com.kasite.core.serviceinterface.module.msg.resp.RespMsgQueueList;

import tk.mybatis.mapper.common.Mapper;

/**
 * 
 * @className: IMsgQueueMapper
 * @author: zwl
 * @date: 2018年11月13日 下午10:29:51
 */
public interface IMsgQueueMapper extends Mapper<MsgQueue>{
	@Select("SELECT * FROM M_MSGQUEUE M where preSendTime < now() or preSendTime=now()")
	List<MsgQueue> querySendMsg(); 
	@Select({"<script>",
		"SELECT * FROM M_MSGQUEUE M ",
		"<where>",
			"<if test=\"queueList.msgId != null and queueList.msgId != ''\">",
				"<![CDATA[ AND msgId = #{queueList.msgId} ]]>",
			"</if>",
			"<if test=\"queueList.modeId != null and queueList.modeId != ''\">",
				"<![CDATA[ AND modeId = #{queueList.modeId} ]]>",
			"</if>",
			"<if test=\"queueList.channelId != null and queueList.channelId != ''\">",
				"<![CDATA[ AND channelId = #{queueList.channelId} ]]>",
			"</if>",
			"<if test=\"queueList.msgType != null and queueList.msgType != ''\">",
				"<![CDATA[ AND msgType = #{queueList.msgType} ]]>",
			"</if>",
			"<if test=\"queueList.modeType != null and queueList.modeType != ''\">",
				"<![CDATA[ AND modeType = #{queueList.modeType} ]]>",
			"</if>",
			"<if test=\"queueList.cardNo != null and queueList.cardNo != ''\">",
				"<![CDATA[ AND cardNo = #{queueList.cardNo} ]]>",
			"</if>",
			"<if test=\"queueList.cardType != null and queueList.cardType != ''\">",
				"<![CDATA[ AND cardType = #{queueList.cardType} ]]>",
			"</if>",
			"<if test=\"queueList.openId != null and queueList.openId != ''\">",
				"<![CDATA[ AND openId = #{queueList.openId} ]]>",
			"</if>",
			"<if test=\"queueList.mobile != null and queueList.mobile != ''\">",
				"<![CDATA[ AND mobile = #{queueList.mobile} ]]>",
			"</if>",
			"<if test=\"queueList.orderId != null and queueList.orderId != ''\">",
				"<![CDATA[ AND orderId = #{queueList.orderId} ]]>",
			"</if>",
			"<if test=\"queueList.state != null and queueList.state != ''\">",
				"<![CDATA[ AND state = #{queueList.state} ]]>",
			"</if>",
			"<if test=\"queueList.operatorId != null and queueList.operatorId != ''\">",
				"<![CDATA[ AND operatorId = #{queueList.operatorId} ]]>",
			"</if>",
			"<if test=\"queueList.orgId != null and queueList.orgId != ''\">",
				"<![CDATA[ AND hosId = #{queueList.orgId} ]]>",
			"</if>",
		"</where>",
	"</script>"})
	List<RespMsgQueueList> queryMsgList(@Param("queueList")ReqMsgQueueList queueList); 
	@Select({"<script>",
		"SELECT * FROM M_MSGQUEUE_RECORD M ",
		"<where>",
			"<if test=\"queueList.msgId != null and queueList.msgId != ''\">",
				"<![CDATA[ AND msgId = #{queueList.msgId} ]]>",
			"</if>",
			"<if test=\"queueList.modeId != null and queueList.modeId != ''\">",
				"<![CDATA[ AND modeId = #{queueList.modeId} ]]>",
			"</if>",
			"<if test=\"queueList.channelId != null and queueList.channelId != ''\">",
				"<![CDATA[ AND channelId = #{queueList.channelId} ]]>",
			"</if>",
			"<if test=\"queueList.msgType != null and queueList.msgType != ''\">",
				"<![CDATA[ AND msgType = #{queueList.msgType} ]]>",
			"</if>",
			"<if test=\"queueList.modeType != null and queueList.modeType != ''\">",
				"<![CDATA[ AND modeType = #{queueList.modeType} ]]>",
			"</if>",
			"<if test=\"queueList.cardNo != null and queueList.cardNo != ''\">",
				"<![CDATA[ AND cardNo = #{queueList.cardNo} ]]>",
			"</if>",
			"<if test=\"queueList.cardType != null and queueList.cardType != ''\">",
				"<![CDATA[ AND cardType = #{queueList.cardType} ]]>",
			"</if>",
			"<if test=\"queueList.openId != null and queueList.openId != ''\">",
				"<![CDATA[ AND openId = #{queueList.openId} ]]>",
			"</if>",
			"<if test=\"queueList.mobile != null and queueList.mobile != ''\">",
				"<![CDATA[ AND mobile = #{queueList.mobile} ]]>",
			"</if>",
			"<if test=\"queueList.orderId != null and queueList.orderId != ''\">",
				"<![CDATA[ AND orderId = #{queueList.orderId} ]]>",
			"</if>",
			"<if test=\"queueList.state != null and queueList.state != ''\">",
				"<![CDATA[ AND state = #{queueList.state} ]]>",
			"</if>",
			"<if test=\"queueList.operatorId != null and queueList.operatorId != ''\">",
				"<![CDATA[ AND operatorId = #{queueList.operatorId} ]]>",
			"</if>",
			"<if test=\"queueList.orgId != null and queueList.orgId != ''\">",
				"<![CDATA[ AND hosId = #{queueList.orgId} ]]>",
			"</if>",
		"</where>",
	"</script>"})
	List<RespMsgQueueList> queryMsgRecordList(@Param("queueList")ReqMsgQueueList queueList); 
	@Select({"<script>",
		"SELECT * FROM(",
		"(SELECT * FROM M_MSGQUEUE M ",
		"<where>",
			"<if test=\"queueList.msgId != null and queueList.msgId != ''\">",
				"<![CDATA[ AND msgId = #{queueList.msgId} ]]>",
			"</if>",
			"<if test=\"queueList.modeId != null and queueList.modeId != ''\">",
				"<![CDATA[ AND modeId = #{queueList.modeId} ]]>",
			"</if>",
			"<if test=\"queueList.channelId != null and queueList.channelId != ''\">",
				"<![CDATA[ AND channelId = #{queueList.channelId} ]]>",
			"</if>",
			"<if test=\"queueList.msgType != null and queueList.msgType != ''\">",
				"<![CDATA[ AND msgType = #{queueList.msgType} ]]>",
			"</if>",
			"<if test=\"queueList.modeType != null and queueList.modeType != ''\">",
				"<![CDATA[ AND modeType = #{queueList.modeType} ]]>",
			"</if>",
			"<if test=\"queueList.cardNo != null and queueList.cardNo != ''\">",
				"<![CDATA[ AND cardNo = #{queueList.cardNo} ]]>",
			"</if>",
			"<if test=\"queueList.cardType != null and queueList.cardType != ''\">",
				"<![CDATA[ AND cardType = #{queueList.cardType} ]]>",
			"</if>",
			"<if test=\"queueList.openId != null and queueList.openId != ''\">",
				"<![CDATA[ AND openId = #{queueList.openId} ]]>",
			"</if>",
			"<if test=\"queueList.mobile != null and queueList.mobile != ''\">",
				"<![CDATA[ AND mobile = #{queueList.mobile} ]]>",
			"</if>",
			"<if test=\"queueList.orderId != null and queueList.orderId != ''\">",
				"<![CDATA[ AND orderId = #{queueList.orderId} ]]>",
			"</if>",
			"<if test=\"queueList.state != null and queueList.state != ''\">",
				"<![CDATA[ AND state = #{queueList.state} ]]>",
			"</if>",
			"<if test=\"queueList.operatorId != null and queueList.operatorId != ''\">",
				"<![CDATA[ AND operatorId = #{queueList.operatorId} ]]>",
			"</if>",
			"<if test=\"queueList.pId != null and queueList.pId != ''\">",
				"<![CDATA[ AND pId = #{queueList.pId} ]]>",
			"</if>",
			"<if test=\"queueList.orgId != null and queueList.orgId != ''\">",
				"<![CDATA[ AND hosId = #{queueList.orgId} ]]>",
			"</if>",
		"</where>",
		")",
		" UNION ALL ",
		"(",
		"SELECT * FROM M_MSGQUEUE_RECORD M ",
		"<where>",
			"<if test=\"queueList.msgId != null and queueList.msgId != ''\">",
				"<![CDATA[ AND msgId = #{queueList.msgId} ]]>",
			"</if>",
			"<if test=\"queueList.modeId != null and queueList.modeId != ''\">",
				"<![CDATA[ AND modeId = #{queueList.modeId} ]]>",
			"</if>",
			"<if test=\"queueList.channelId != null and queueList.channelId != ''\">",
				"<![CDATA[ AND channelId = #{queueList.channelId} ]]>",
			"</if>",
			"<if test=\"queueList.msgType != null and queueList.msgType != ''\">",
				"<![CDATA[ AND msgType = #{queueList.msgType} ]]>",
			"</if>",
			"<if test=\"queueList.modeType != null and queueList.modeType != ''\">",
				"<![CDATA[ AND modeType = #{queueList.modeType} ]]>",
			"</if>",
			"<if test=\"queueList.cardNo != null and queueList.cardNo != ''\">",
				"<![CDATA[ AND cardNo = #{queueList.cardNo} ]]>",
			"</if>",
			"<if test=\"queueList.cardType != null and queueList.cardType != ''\">",
				"<![CDATA[ AND cardType = #{queueList.cardType} ]]>",
			"</if>",
			"<if test=\"queueList.openId != null and queueList.openId != ''\">",
				"<![CDATA[ AND openId = #{queueList.openId} ]]>",
			"</if>",
			"<if test=\"queueList.mobile != null and queueList.mobile != ''\">",
				"<![CDATA[ AND mobile = #{queueList.mobile} ]]>",
			"</if>",
			"<if test=\"queueList.orderId != null and queueList.orderId != ''\">",
				"<![CDATA[ AND orderId = #{queueList.orderId} ]]>",
			"</if>",
			"<if test=\"queueList.state != null and queueList.state != ''\">",
				"<![CDATA[ AND state = #{queueList.state} ]]>",
			"</if>",
			"<if test=\"queueList.operatorId != null and queueList.operatorId != ''\">",
				"<![CDATA[ AND operatorId = #{queueList.operatorId} ]]>",
			"</if>",
			"<if test=\"queueList.pId != null and queueList.pId != ''\">",
				"<![CDATA[ AND pId = #{queueList.pId} ]]>",
			"</if>",
			"<if test=\"queueList.orgId != null and queueList.orgId != ''\">",
				"<![CDATA[ AND hosId = #{queueList.orgId} ]]>",
			"</if>",
		"</where>",
		")",
		")AS a ORDER BY a.CREATETIME DESC LIMIT #{pIndex},#{pSize}",
	"</script>"})
	List<RespMsgQueueList> queryMsgListUnion(@Param("queueList")ReqMsgQueueList queueList,@Param("pIndex")int pIndex,@Param("pSize")int pSize); 
	@Select({"<script>",
		"SELECT count(1) FROM(",
		"(SELECT * FROM M_MSGQUEUE M ",
		"<where>",
			"<if test=\"queueList.msgId != null and queueList.msgId != ''\">",
				"<![CDATA[ AND msgId = #{queueList.msgId} ]]>",
			"</if>",
			"<if test=\"queueList.modeId != null and queueList.modeId != ''\">",
				"<![CDATA[ AND modeId = #{queueList.modeId} ]]>",
			"</if>",
			"<if test=\"queueList.channelId != null and queueList.channelId != ''\">",
				"<![CDATA[ AND channelId = #{queueList.channelId} ]]>",
			"</if>",
			"<if test=\"queueList.msgType != null and queueList.msgType != ''\">",
				"<![CDATA[ AND msgType = #{queueList.msgType} ]]>",
			"</if>",
			"<if test=\"queueList.modeType != null and queueList.modeType != ''\">",
				"<![CDATA[ AND modeType = #{queueList.modeType} ]]>",
			"</if>",
			"<if test=\"queueList.cardNo != null and queueList.cardNo != ''\">",
				"<![CDATA[ AND cardNo = #{queueList.cardNo} ]]>",
			"</if>",
			"<if test=\"queueList.cardType != null and queueList.cardType != ''\">",
				"<![CDATA[ AND cardType = #{queueList.cardType} ]]>",
			"</if>",
			"<if test=\"queueList.openId != null and queueList.openId != ''\">",
				"<![CDATA[ AND openId = #{queueList.openId} ]]>",
			"</if>",
			"<if test=\"queueList.mobile != null and queueList.mobile != ''\">",
				"<![CDATA[ AND mobile = #{queueList.mobile} ]]>",
			"</if>",
			"<if test=\"queueList.orderId != null and queueList.orderId != ''\">",
				"<![CDATA[ AND orderId = #{queueList.orderId} ]]>",
			"</if>",
			"<if test=\"queueList.state != null and queueList.state != ''\">",
				"<![CDATA[ AND state = #{queueList.state} ]]>",
			"</if>",
			"<if test=\"queueList.operatorId != null and queueList.operatorId != ''\">",
				"<![CDATA[ AND operatorId = #{queueList.operatorId} ]]>",
			"</if>",
			"<if test=\"queueList.pId != null and queueList.pId != ''\">",
				"<![CDATA[ AND pId = #{queueList.pId} ]]>",
			"</if>",
			"<if test=\"queueList.orgId != null and queueList.orgId != ''\">",
				"<![CDATA[ AND hosId = #{queueList.orgId} ]]>",
			"</if>",
		"</where>",
		")",
		" UNION ALL ",
		"(",
		"SELECT * FROM M_MSGQUEUE_RECORD M ",
		"<where>",
			"<if test=\"queueList.msgId != null and queueList.msgId != ''\">",
				"<![CDATA[ AND msgId = #{queueList.msgId} ]]>",
			"</if>",
			"<if test=\"queueList.modeId != null and queueList.modeId != ''\">",
				"<![CDATA[ AND modeId = #{queueList.modeId} ]]>",
			"</if>",
			"<if test=\"queueList.channelId != null and queueList.channelId != ''\">",
				"<![CDATA[ AND channelId = #{queueList.channelId} ]]>",
			"</if>",
			"<if test=\"queueList.msgType != null and queueList.msgType != ''\">",
				"<![CDATA[ AND msgType = #{queueList.msgType} ]]>",
			"</if>",
			"<if test=\"queueList.modeType != null and queueList.modeType != ''\">",
				"<![CDATA[ AND modeType = #{queueList.modeType} ]]>",
			"</if>",
			"<if test=\"queueList.cardNo != null and queueList.cardNo != ''\">",
				"<![CDATA[ AND cardNo = #{queueList.cardNo} ]]>",
			"</if>",
			"<if test=\"queueList.cardType != null and queueList.cardType != ''\">",
				"<![CDATA[ AND cardType = #{queueList.cardType} ]]>",
			"</if>",
			"<if test=\"queueList.openId != null and queueList.openId != ''\">",
				"<![CDATA[ AND openId = #{queueList.openId} ]]>",
			"</if>",
			"<if test=\"queueList.mobile != null and queueList.mobile != ''\">",
				"<![CDATA[ AND mobile = #{queueList.mobile} ]]>",
			"</if>",
			"<if test=\"queueList.orderId != null and queueList.orderId != ''\">",
				"<![CDATA[ AND orderId = #{queueList.orderId} ]]>",
			"</if>",
			"<if test=\"queueList.state != null and queueList.state != ''\">",
				"<![CDATA[ AND state = #{queueList.state} ]]>",
			"</if>",
			"<if test=\"queueList.operatorId != null and queueList.operatorId != ''\">",
				"<![CDATA[ AND operatorId = #{queueList.operatorId} ]]>",
			"</if>",
			"<if test=\"queueList.pId != null and queueList.pId != ''\">",
				"<![CDATA[ AND pId = #{queueList.pId} ]]>",
			"</if>",
			"<if test=\"queueList.orgId != null and queueList.orgId != ''\">",
				"<![CDATA[ AND hosId = #{queueList.orgId} ]]>",
			"</if>",
		"</where>",
		")",
		")AS a",
	"</script>"})
	int queryMsgQueueCount(@Param("queueList")ReqMsgQueueList queueList); 

}
