kasite:
    appConfig:
        #是否开启中心连接
        isConnectionKastieCenter: true
        #配置中心地址 如果不开启连接中心的时候可以注释 中心的url地址
        centerUrl: https://verification.kasitesoft.com,http://verification2.kasitesoft.com
        #配置中心申请的appId（必须）
        appId: KASTIE-CLIENT-BALANCEOFACCOUNT.5141
        #医院名称
        appName: 泉州爱尔眼科医院对账系统V1.0
        #配置中心申请的密码（必须）
        appSecret: 2LdBF9viPg
        #组织机构代码（必须）
        orgCode: 5141
        #本地保存配置文件的目录（必须）
        configPath: C:/Users/Administrator/Desktop
        #中心获取的配置 公钥 （必须）
        publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtlR82WKjACp0oJfX2biFJOaZcM86GWt4/CoQbv5bRkzSZquEQFHYMAonfxk+bq0UlC/2O5BXT1NYIcYS4vFjXN/B4TWw7qe5UDj0vIO9XCeoA68X9k80lU9d+rG7qvBQVJnmYJnkbN9IDhFnZM9fvWqKiKRx78BQmeC+PQ/3+eqESMmeOkJv+3OBJbDQ9hca9ynefucYGrN+eDrI5aM9lmMBUd2ws7WEYdc6VainjgCEYvIWFrEeStnbtQzcHt1XouiFcv17PX4up5y1vsuQM6AA+QM4JBHTL/QnP8d8ZLj4CHITxOXB/gvBsOlg82KW0VEGwYan4lY+oZm8wNj8ewIDAQAB

    #定时任务是否启动（默认都为true）
    jobStartStateMap:
        #每日凌晨3点下载HIS账单
        DownloadHisBills: true
        #每日10.40分开始生成每日汇总账单
        GenerateEveryDayBills: true
        #由于全流程汇总时使用到了P_BILL表的数据进行校准,所以全流程汇总的作业应该晚于微信账单的下载
        #目前暂定10.20分
        GenerateQlcBills: true
        #每日10.35分开始生成三方汇总账单明细数据
        GenerateThreePartyBills: true

#请填写医院hosId
info:
    orgCode: 5141

spring:
    #SpringAdmin 的配置
    boot:
      admin:
        client:
          read-timeout: 30000
          connect-timeout: 30000
          instance:
        #客户端要显示的工程名 医院全称+统一对账系统
            name: 泉州爱尔医院统一对账系统
        #客户端的工程部署地址
            service-url: http://218.5.173.25:9091/balabceofaccount/bill/threeParty/everyDayBill.html
        # http://外网ip或域名/actuator
            management-url: http://218.5.173.25:9091/balabceofaccount/actuator
        # http://外网ip或域名/actuator/health
            health-url: http://218.5.173.25:9091/balabceofaccount/actuator/health
        #正式线URL地址 地址 https://springadmin.kasitesoft.com 默认配 默认配置开发线，记得修改# 开发线线URL地址 地址 http://119.23.210.15:9999#向服务端注册的地址
          url: http://119.23.210.15:9999
          username: admin
          password: kst.2018
    #双数据源的配置，如果不需要删除slave段代码即可
    datasource:
        master:
            saveSqlLog: true
            showSql: true
            alias: hos
            ip: 127.0.0.1
            databaseName: aeykyy
            url: jdbc:mysql://127.0.0.1:3306/aeykyy?allowMultiQueries=true&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=UTF-8&useLOBs=false
            username: root
            password: 123456
            driverClassName: com.mysql.jdbc.Driver
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=50000
        loginUsername: kasite
        loginPassword: kasite_0
    devtools:
      restart:
        enabled: true
dataBase:
    dbType: MYSQL

#HIS相关配置信息
HisConfig:
    #His账单接口地址
    url: http://10.84.4.6:8089/HisWebService1.asmx
    #HIS账单接口实现类名,通过此值动态配置调用的实现类
    instance: HisService_FJQZAEYKYY
    #HIS接口调用具体实现方法 SOAP或HL7 如需拓展请callMe
    type: SOAP

#mybatis xml和mapper读取
mybatis:
  mapper-locations: classpath:mapper/fjqzaeykyy/mysql/*.xml
  type-aliases-package: com.kasite.client.hospay.module.bill.dao

#配置分页插件pageHelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count = countSql

#认证的配置
AuthenticatorConfig:
    userName: aeykyy
    hostName: aeykyy
    #生成秘钥后填在这边即可
    secret: JBAGBIZ7HDXB7UEW
    #谷歌验证码，如果医院不想使用谷歌验证软件，可以在这边填写默认值（不建议使用默认值的方式）
    passWord:
    #是否限制前端汇总时间的 0否 1是 默认1
    isDefault: 1

#operationButton页面操作按钮展示参数 0展示所有 1不展示冲正 2不展示退费 3不展示财务调账
#默认 1 不展示冲正
#后面四个参数为页面展示  1展示 0隐藏
Page:
    operationButton: 1
    everyDayBillIsShow: 1
    everyDayBillDetailIsShow: 1
    classifySummaryBillIsShow: 1
    alwaysRefundIsShow: 0

#几方汇总的判断参数 3三方汇总 2两方汇总
#默认使用 3三方汇总
several:
    parties: 3

#Excel文件保存路径
file:
    path: D://BillExcel

#统一对账平台配置参数
balanceConfig:
    #账单列表的操作人是否已json展示 0不 1是 默认0
    operationJson: 0


#微信配置
ChannelWXConfig:
        # 查询订单URL
        queryOrderUrl: https://api.mch.weixin.qq.com/pay/orderquery
        # 退款URL
        refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
        # 公众号AppId
        subAppId: wx474c4a73fc0452b9
        # 子商户ID
        subMerchantId: 1248246801
        # 父商户秘钥
        parentMerchantKey: 12345678123456781234567812345678
        # 父商户AppId
        parentAppId: wxd6507cf4c191b6a9
        # 父商户Id
        parentMerchantId: 1235595402
        # 退款证书
        certPath: F://cert//apiclient_cert.p12
        notifyUrl:

#支付宝配置
ChannelZFBConfig:
        # 支付宝网关
        alipayGateWay: https://openapi.alipay.com/gateway.do
        # 支付宝AppId
        appId: 2017083108475325
        # 应用私钥
        privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALbVMSjJHTvoAXAqTr74iM6cYOMM6MrvWU7xOIsE1SUSCxb/xNVeFGY0OyybPnUG46nT9VkuDZwoj8/8weRUfpGxaETTls2rA/E3SnzyY9YpwTTd/8hWIJgA2VMQQLA5a1bWQ82yix3GhyNgS9dbpUf2+beM3NIWqYUTxItan6vNAgMBAAECgYBrbaFRAbr3tD8EFRfoBkj8fc5AGxm+BB1J0VsT9Gb5PTze6rJRXNJHq3EJqL5uLPogk7aaDAFbPEokP7P94dfr6xijAd8D61buLUzgBkJIHRY7L4c+FCouA9/TnRiD0tpQ60GILM+shlxruBeixRJHLgCN1vUzWerzJVE7oKA90QJBAPZleXXcEauFYV7q+w0Ql7ns9I+mXluxAojwGxd8XtreuVo59W3SVnGr56TKuHlKUICHWXxk0GTINj8pXabpbf8CQQC99XwGoKmUrrWvFQqVdFXDGWo0AdYUA/qHzPtBoLSI3ovX+hRgibO/Dtxlq4rQ4KRw5Ax705msXDwwFGeUhT4zAkEA0MBAG16LienDCQvEDtmT8m2S9XFaWAyrvSDPkyJHqt8v4gVgrd6aZkviQXeOuxP/CCWj5wPymrAVZYXCVntGOQJAHDPQICPGSZ7OtpnHIn1NJlQlomcLY5lbnsHeI9Y6N3/i/0PPtq17FEiejDG1wGE5yNDy0YeO7zoabYD6B+DoZQJAL2atIDvo3F8/lpGE5z9AaYBis6b5DtinlQphxSN/5xjCvGn5laRlA383/PJIPAFHFsz/zgVyyL5zVdUJf5km3Q==
        # 应用公钥
        publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC21TEoyR076AFwKk6++IjOnGDjDOjK71lO8TiLBNUlEgsW/8TVXhRmNDssmz51BuOp0/VZLg2cKI/P/MHkVH6RsWhE05bNqwPxN0p88mPWKcE03f/IViCYANlTEECwOWtW1kPNsosdxocjYEvXW6VH9vm3jNzSFqmFE8SLWp+rzQIDAQAB
        # 支付宝公钥
        alipayPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDI6d306Q8fIfCOaTXyiUeJHkrIvYISRcc73s3vF1ZT7XN8RNPwJxo8pWaJMmvyTn9N4HQ632qJBVHf8sxHi
        # 签名类型 默认RSA2 请根据支付宝生活窗的实际进行修改
        signType: RSA2