package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 附件 This class was generated by MyBatis Generator. This class corresponds to
 * the database table QY_ATTACHMENT
 */
@Table(name = "QY_ATTACHMENT")
public class Attachment implements Serializable {
	/**
	 * 主键ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	/**
	 * 附件对应的订单ID、会议ID等
	 */
	@Column(name = "UID")
	private String uid;

	/**
	 * 附件地址
	 */
	@Column(name = "URL")
	private String url;

	/**
	 * 附件名称
	 */
	@Column(name = "NAME")
	private String name;

	/**
	 * 状态 默认0=有效 1=无效
	 */
	@Column(name = "STATUS")
	private Integer status;

	/**
	 * 创建时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * 附件类型
	 */
	@Column(name = "ATTACHMENTTYPE")
	private Integer attachmenttype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_ATTACHMENT
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ATTACHMENT.ID
	 *
	 * @return the value of QY_ATTACHMENT.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ATTACHMENT.ID
	 *
	 * @param id the value for QY_ATTACHMENT.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ATTACHMENT.UID
	 *
	 * @return the value of QY_ATTACHMENT.UID
	 *
	 * @mbg.generated
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ATTACHMENT.UID
	 *
	 * @param uid the value for QY_ATTACHMENT.UID
	 *
	 * @mbg.generated
	 */
	public void setUid(String uid) {
		this.uid = uid == null ? null : uid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ATTACHMENT.URL
	 *
	 * @return the value of QY_ATTACHMENT.URL
	 *
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ATTACHMENT.URL
	 *
	 * @param url the value for QY_ATTACHMENT.URL
	 *
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ATTACHMENT.NAME
	 *
	 * @return the value of QY_ATTACHMENT.NAME
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ATTACHMENT.NAME
	 *
	 * @param name the value for QY_ATTACHMENT.NAME
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ATTACHMENT.STATUS
	 *
	 * @return the value of QY_ATTACHMENT.STATUS
	 *
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ATTACHMENT.STATUS
	 *
	 * @param status the value for QY_ATTACHMENT.STATUS
	 *
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ATTACHMENT.INSERTTIME
	 *
	 * @return the value of QY_ATTACHMENT.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ATTACHMENT.INSERTTIME
	 *
	 * @param inserttime the value for QY_ATTACHMENT.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	public Integer getAttachmenttype() {
		return attachmenttype;
	}

	public void setAttachmenttype(Integer attachmenttype) {
		this.attachmenttype = attachmenttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_ATTACHMENT
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", uid=").append(uid);
		sb.append(", url=").append(url);
		sb.append(", name=").append(name);
		sb.append(", status=").append(status);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}