package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 故障报修 This class was generated by MyBatis Generator. This class corresponds to
 * the database table QY_FAULT_REPAIR
 */
@Table(name = "QY_FAULT_REPAIR")
public class FaultRepair implements Serializable {
	/**
	 * 主键ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	/**
	 * 订单编号
	 */
	@Column(name = "ORDERID")
	private String orderid;

	/**
	 * 故障标题
	 */
	@Column(name = "TITLE")
	private String title;

	/**
	 * 故障描述
	 */
	@Column(name = "CONTENT")
	private String content;

	/**
	 * 申请人ID
	 */
	@Column(name = "APPLYERID")
	private String applyerid;

	/**
	 * 申请人姓名
	 */
	@Column(name = "APPLYERNAME")
	private String applyername;

	/**
	 * 受理人/分配人 ID 多个用逗号分隔
	 */
	@Column(name = "RECEIVERID")
	private String receiverid;

	/**
	 * 受理人/分配人 姓名 多个用逗号分隔
	 */
	@Column(name = "RECEIVERNAME")
	private String receivername;

	/**
	 * 维修人ID 多个逗号分隔
	 */
	@Column(name = "REPAIRERID")
	private String repairerid;

	/**
	 * 维修人姓名 多个逗号分隔
	 */
	@Column(name = "REPAIRERNAME")
	private String repairername;

	/**
	 * 验收结果
	 */
	@Column(name = "RESULT")
	private String result;

	/**
	 * 订单状态 0=待受理 1=处理中 2=已驳回 3=已完成 4=已验收
	 */
	@Column(name = "STATUS")
	private Integer status;

	/**
	 * 申请时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * 修改时间
	 */
	@Column(name = "UPDATETIME")
	private String updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_FAULT_REPAIR
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.ID
	 *
	 * @return the value of QY_FAULT_REPAIR.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.ID
	 *
	 * @param id the value for QY_FAULT_REPAIR.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.ORDERID
	 *
	 * @return the value of QY_FAULT_REPAIR.ORDERID
	 *
	 * @mbg.generated
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.ORDERID
	 *
	 * @param orderid the value for QY_FAULT_REPAIR.ORDERID
	 *
	 * @mbg.generated
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid == null ? null : orderid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.TITLE
	 *
	 * @return the value of QY_FAULT_REPAIR.TITLE
	 *
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.TITLE
	 *
	 * @param title the value for QY_FAULT_REPAIR.TITLE
	 *
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.CONTENT
	 *
	 * @return the value of QY_FAULT_REPAIR.CONTENT
	 *
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.CONTENT
	 *
	 * @param content the value for QY_FAULT_REPAIR.CONTENT
	 *
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.APPLYERID
	 *
	 * @return the value of QY_FAULT_REPAIR.APPLYERID
	 *
	 * @mbg.generated
	 */
	public String getApplyerid() {
		return applyerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.APPLYERID
	 *
	 * @param applyerid the value for QY_FAULT_REPAIR.APPLYERID
	 *
	 * @mbg.generated
	 */
	public void setApplyerid(String applyerid) {
		this.applyerid = applyerid == null ? null : applyerid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.APPLYERNAME
	 *
	 * @return the value of QY_FAULT_REPAIR.APPLYERNAME
	 *
	 * @mbg.generated
	 */
	public String getApplyername() {
		return applyername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.APPLYERNAME
	 *
	 * @param applyername the value for QY_FAULT_REPAIR.APPLYERNAME
	 *
	 * @mbg.generated
	 */
	public void setApplyername(String applyername) {
		this.applyername = applyername == null ? null : applyername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.RECEIVERID
	 *
	 * @return the value of QY_FAULT_REPAIR.RECEIVERID
	 *
	 * @mbg.generated
	 */
	public String getReceiverid() {
		return receiverid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.RECEIVERID
	 *
	 * @param receiverid the value for QY_FAULT_REPAIR.RECEIVERID
	 *
	 * @mbg.generated
	 */
	public void setReceiverid(String receiverid) {
		this.receiverid = receiverid == null ? null : receiverid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.RECEIVERNAME
	 *
	 * @return the value of QY_FAULT_REPAIR.RECEIVERNAME
	 *
	 * @mbg.generated
	 */
	public String getReceivername() {
		return receivername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.RECEIVERNAME
	 *
	 * @param receivername the value for QY_FAULT_REPAIR.RECEIVERNAME
	 *
	 * @mbg.generated
	 */
	public void setReceivername(String receivername) {
		this.receivername = receivername == null ? null : receivername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.REPAIRERID
	 *
	 * @return the value of QY_FAULT_REPAIR.REPAIRERID
	 *
	 * @mbg.generated
	 */
	public String getRepairerid() {
		return repairerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.REPAIRERID
	 *
	 * @param repairerid the value for QY_FAULT_REPAIR.REPAIRERID
	 *
	 * @mbg.generated
	 */
	public void setRepairerid(String repairerid) {
		this.repairerid = repairerid == null ? null : repairerid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.REPAIRERNAME
	 *
	 * @return the value of QY_FAULT_REPAIR.REPAIRERNAME
	 *
	 * @mbg.generated
	 */
	public String getRepairername() {
		return repairername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.REPAIRERNAME
	 *
	 * @param repairername the value for QY_FAULT_REPAIR.REPAIRERNAME
	 *
	 * @mbg.generated
	 */
	public void setRepairername(String repairername) {
		this.repairername = repairername == null ? null : repairername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.RESULT
	 *
	 * @return the value of QY_FAULT_REPAIR.RESULT
	 *
	 * @mbg.generated
	 */
	public String getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.RESULT
	 *
	 * @param result the value for QY_FAULT_REPAIR.RESULT
	 *
	 * @mbg.generated
	 */
	public void setResult(String result) {
		this.result = result == null ? null : result.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.STATUS
	 *
	 * @return the value of QY_FAULT_REPAIR.STATUS
	 *
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.STATUS
	 *
	 * @param status the value for QY_FAULT_REPAIR.STATUS
	 *
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.INSERTTIME
	 *
	 * @return the value of QY_FAULT_REPAIR.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.INSERTTIME
	 *
	 * @param inserttime the value for QY_FAULT_REPAIR.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_REPAIR.UPDATETIME
	 *
	 * @return the value of QY_FAULT_REPAIR.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_REPAIR.UPDATETIME
	 *
	 * @param updatetime the value for QY_FAULT_REPAIR.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_FAULT_REPAIR
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", orderid=").append(orderid);
		sb.append(", title=").append(title);
		sb.append(", content=").append(content);
		sb.append(", applyerid=").append(applyerid);
		sb.append(", applyername=").append(applyername);
		sb.append(", receiverid=").append(receiverid);
		sb.append(", receivername=").append(receivername);
		sb.append(", repairerid=").append(repairerid);
		sb.append(", repairername=").append(repairername);
		sb.append(", result=").append(result);
		sb.append(", status=").append(status);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", updatetime=").append(updatetime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}