package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 故障受理流程 This class was generated by MyBatis Generator. This class corresponds
 * to the database table QY_FAULT_PROCESS
 */
@Table(name = "QY_FAULT_PROCESS")
public class FaultProcess implements Serializable {
	/**
	 * 主键ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	/**
	 * 故障单编号
	 */
	@Column(name = "ORDERID")
	private String orderid;

	/**
	 * 备注
	 */
	@Column(name = "REMARK")
	private String remark;

	/**
	 * 插入时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_FAULT_PROCESS
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_PROCESS.ID
	 *
	 * @return the value of QY_FAULT_PROCESS.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_PROCESS.ID
	 *
	 * @param id the value for QY_FAULT_PROCESS.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_PROCESS.ORDERID
	 *
	 * @return the value of QY_FAULT_PROCESS.ORDERID
	 *
	 * @mbg.generated
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_PROCESS.ORDERID
	 *
	 * @param orderid the value for QY_FAULT_PROCESS.ORDERID
	 *
	 * @mbg.generated
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid == null ? null : orderid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_PROCESS.REMARK
	 *
	 * @return the value of QY_FAULT_PROCESS.REMARK
	 *
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_PROCESS.REMARK
	 *
	 * @param remark the value for QY_FAULT_PROCESS.REMARK
	 *
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_FAULT_PROCESS.INSERTTIME
	 *
	 * @return the value of QY_FAULT_PROCESS.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_FAULT_PROCESS.INSERTTIME
	 *
	 * @param inserttime the value for QY_FAULT_PROCESS.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_FAULT_PROCESS
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", orderid=").append(orderid);
		sb.append(", remark=").append(remark);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}