package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 会议设备管理 This class was generated by MyBatis Generator. This class corresponds
 * to the database table QY_MEETING_EQUIPMENT
 */
@Table(name = "QY_MEETING_EQUIPMENT")
public class MeetingEquipment implements Serializable {
	/**
	 * 主键ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	/**
	 * 设备名称
	 */
	@Column(name = "NAME")
	private String name;

	/**
	 * 状态 默认0=正常 1=删除
	 */
	@Column(name = "STATUS")
	private Integer status;

	/**
	 * 插入时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * 修改时间
	 */
	@Column(name = "UPDATETIME")
	private String updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_MEETING_EQUIPMENT
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_EQUIPMENT.ID
	 *
	 * @return the value of QY_MEETING_EQUIPMENT.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_EQUIPMENT.ID
	 *
	 * @param id the value for QY_MEETING_EQUIPMENT.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_EQUIPMENT.NAME
	 *
	 * @return the value of QY_MEETING_EQUIPMENT.NAME
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_EQUIPMENT.NAME
	 *
	 * @param name the value for QY_MEETING_EQUIPMENT.NAME
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_EQUIPMENT.STATUS
	 *
	 * @return the value of QY_MEETING_EQUIPMENT.STATUS
	 *
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_EQUIPMENT.STATUS
	 *
	 * @param status the value for QY_MEETING_EQUIPMENT.STATUS
	 *
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_EQUIPMENT.INSERTTIME
	 *
	 * @return the value of QY_MEETING_EQUIPMENT.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_EQUIPMENT.INSERTTIME
	 *
	 * @param inserttime the value for QY_MEETING_EQUIPMENT.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_EQUIPMENT.UPDATETIME
	 *
	 * @return the value of QY_MEETING_EQUIPMENT.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_EQUIPMENT.UPDATETIME
	 *
	 * @param updatetime the value for QY_MEETING_EQUIPMENT.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_MEETING_EQUIPMENT
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", status=").append(status);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", updatetime=").append(updatetime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}