package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 会议签到、签退 This class was generated by MyBatis Generator. This class corresponds
 * to the database table QY_MEETING_SIGN
 */
@Table(name = "QY_MEETING_SIGN")
public class MeetingSign implements Serializable {
	/**
	 * 主键ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	/**
	 * 附件对应的订单ID、会议ID等
	 */
	@Column(name = "UID")
	private String uid;

	/**
	 * 纬度
	 */
	@Column(name = "LATITUDE")
	private String latitude;

	/**
	 * 维度
	 */
	@Column(name = "LONGITUDE")
	private String longitude;

	/**
	 * 位置精度
	 */
	@Column(name = "ACCURACY")
	private String accuracy;

	/**
	 * 签到、签退地点名称
	 */
	@Column(name = "PLACE")
	private String place;

	/**
	 * 签到人ID
	 */
	@Column(name = "MEMBERID")
	private String memberid;

	/**
	 * 签到人姓名
	 */
	@Column(name = "MEMBERNAME")
	private String membername;

	/**
	 * 签到、签退时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * 类型 0=签到 1=签退
	 */
	@Column(name = "SIGNTYPE")
	private Integer signtype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_MEETING_SIGN
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.ID
	 *
	 * @return the value of QY_MEETING_SIGN.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.ID
	 *
	 * @param id the value for QY_MEETING_SIGN.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.UID
	 *
	 * @return the value of QY_MEETING_SIGN.UID
	 *
	 * @mbg.generated
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.UID
	 *
	 * @param uid the value for QY_MEETING_SIGN.UID
	 *
	 * @mbg.generated
	 */
	public void setUid(String uid) {
		this.uid = uid == null ? null : uid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.LATITUDE
	 *
	 * @return the value of QY_MEETING_SIGN.LATITUDE
	 *
	 * @mbg.generated
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.LATITUDE
	 *
	 * @param latitude the value for QY_MEETING_SIGN.LATITUDE
	 *
	 * @mbg.generated
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude == null ? null : latitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.LONGITUDE
	 *
	 * @return the value of QY_MEETING_SIGN.LONGITUDE
	 *
	 * @mbg.generated
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.LONGITUDE
	 *
	 * @param longitude the value for QY_MEETING_SIGN.LONGITUDE
	 *
	 * @mbg.generated
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude == null ? null : longitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.ACCURACY
	 *
	 * @return the value of QY_MEETING_SIGN.ACCURACY
	 *
	 * @mbg.generated
	 */
	public String getAccuracy() {
		return accuracy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.ACCURACY
	 *
	 * @param accuracy the value for QY_MEETING_SIGN.ACCURACY
	 *
	 * @mbg.generated
	 */
	public void setAccuracy(String accuracy) {
		this.accuracy = accuracy == null ? null : accuracy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.PLACE
	 *
	 * @return the value of QY_MEETING_SIGN.PLACE
	 *
	 * @mbg.generated
	 */
	public String getPlace() {
		return place;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.PLACE
	 *
	 * @param place the value for QY_MEETING_SIGN.PLACE
	 *
	 * @mbg.generated
	 */
	public void setPlace(String place) {
		this.place = place == null ? null : place.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.MEMBERID
	 *
	 * @return the value of QY_MEETING_SIGN.MEMBERID
	 *
	 * @mbg.generated
	 */
	public String getMemberid() {
		return memberid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.MEMBERID
	 *
	 * @param memberid the value for QY_MEETING_SIGN.MEMBERID
	 *
	 * @mbg.generated
	 */
	public void setMemberid(String memberid) {
		this.memberid = memberid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.MEMBERNAME
	 *
	 * @return the value of QY_MEETING_SIGN.MEMBERNAME
	 *
	 * @mbg.generated
	 */
	public String getMembername() {
		return membername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.MEMBERNAME
	 *
	 * @param membername the value for QY_MEETING_SIGN.MEMBERNAME
	 *
	 * @mbg.generated
	 */
	public void setMembername(String membername) {
		this.membername = membername == null ? null : membername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.INSERTTIME
	 *
	 * @return the value of QY_MEETING_SIGN.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.INSERTTIME
	 *
	 * @param inserttime the value for QY_MEETING_SIGN.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.SIGNTYPE
	 *
	 * @return the value of QY_MEETING_SIGN.SIGNTYPE
	 *
	 * @mbg.generated
	 */
	public Integer getSigntype() {
		return signtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.SIGNTYPE
	 *
	 * @param signtype the value for QY_MEETING_SIGN.SIGNTYPE
	 *
	 * @mbg.generated
	 */
	public void setSigntype(Integer signtype) {
		this.signtype = signtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_MEETING_SIGN
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", uid=").append(uid);
		sb.append(", latitude=").append(latitude);
		sb.append(", longitude=").append(longitude);
		sb.append(", accuracy=").append(accuracy);
		sb.append(", place=").append(place);
		sb.append(", memberid=").append(memberid);
		sb.append(", membername=").append(membername);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", signtype=").append(signtype);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}