package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 成员积分 This class was generated by MyBatis Generator. This class corresponds to
 * the database table QY_MEMBER_CREDITS_INFO
 */
@Table(name = "QY_MEMBER_CREDITS_INFO")
public class MemberCreditsInfo implements Serializable {
	/**
	 * 主键ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	/**
	 * 成员ID
	 */
	@Column(name = "MEMBERID")
	private String memberid;

	/**
	 * 会议id
	 */
	@Column(name = "MEETINGID")
	private String meetingid;

	/**
	 * 会议主题
	 */
	@Column(name = "MEETINGTITLE")
	private String meetingtitle;

	/**
	 * 学分
	 */
	@Column(name = "CREDITS")
	private Integer credits;

	/**
	 * 插入时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * 修改时间
	 */
	@Column(name = "UPDATETIME")
	private String updatetime;

	/**
	 * 会议日期
	 */
	@Column(name = "MEETINGDATE")
	private String meetingdate;

	/**
	 * 会议开始时间
	 */
	@Column(name = "TIMESTART")
	private String timestart;

	/**
	 * 会议结束时间
	 */
	@Column(name = "TIMEEND")
	private String timeend;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_MEMBER_CREDITS_INFO
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS_INFO.ID
	 *
	 * @return the value of QY_MEMBER_CREDITS_INFO.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS_INFO.ID
	 *
	 * @param id the value for QY_MEMBER_CREDITS_INFO.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS_INFO.MEMBERID
	 *
	 * @return the value of QY_MEMBER_CREDITS_INFO.MEMBERID
	 *
	 * @mbg.generated
	 */
	public String getMemberid() {
		return memberid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS_INFO.MEMBERID
	 *
	 * @param memberid the value for QY_MEMBER_CREDITS_INFO.MEMBERID
	 *
	 * @mbg.generated
	 */
	public void setMemberid(String memberid) {
		this.memberid = memberid == null ? null : memberid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS_INFO.MEETINGID
	 *
	 * @return the value of QY_MEMBER_CREDITS_INFO.MEETINGID
	 *
	 * @mbg.generated
	 */
	public String getMeetingid() {
		return meetingid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS_INFO.MEETINGID
	 *
	 * @param meetingid the value for QY_MEMBER_CREDITS_INFO.MEETINGID
	 *
	 * @mbg.generated
	 */
	public void setMeetingid(String meetingid) {
		this.meetingid = meetingid == null ? null : meetingid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS_INFO.MEETINGTITLE
	 *
	 * @return the value of QY_MEMBER_CREDITS_INFO.MEETINGTITLE
	 *
	 * @mbg.generated
	 */
	public String getMeetingtitle() {
		return meetingtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS_INFO.MEETINGTITLE
	 *
	 * @param meetingtitle the value for QY_MEMBER_CREDITS_INFO.MEETINGTITLE
	 *
	 * @mbg.generated
	 */
	public void setMeetingtitle(String meetingtitle) {
		this.meetingtitle = meetingtitle == null ? null : meetingtitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS_INFO.CREDITS
	 *
	 * @return the value of QY_MEMBER_CREDITS_INFO.CREDITS
	 *
	 * @mbg.generated
	 */
	public Integer getCredits() {
		return credits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS_INFO.CREDITS
	 *
	 * @param credits the value for QY_MEMBER_CREDITS_INFO.CREDITS
	 *
	 * @mbg.generated
	 */
	public void setCredits(Integer credits) {
		this.credits = credits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS_INFO.INSERTTIME
	 *
	 * @return the value of QY_MEMBER_CREDITS_INFO.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS_INFO.INSERTTIME
	 *
	 * @param inserttime the value for QY_MEMBER_CREDITS_INFO.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS_INFO.UPDATETIME
	 *
	 * @return the value of QY_MEMBER_CREDITS_INFO.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS_INFO.UPDATETIME
	 *
	 * @param updatetime the value for QY_MEMBER_CREDITS_INFO.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	public String getMeetingdate() {
		return meetingdate;
	}

	public void setMeetingdate(String meetingdate) {
		this.meetingdate = meetingdate;
	}

	public String getTimestart() {
		return timestart;
	}

	public void setTimestart(String timestart) {
		this.timestart = timestart;
	}

	public String getTimeend() {
		return timeend;
	}

	public void setTimeend(String timeend) {
		this.timeend = timeend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_MEMBER_CREDITS_INFO
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", memberid=").append(memberid);
		sb.append(", meetingid=").append(meetingid);
		sb.append(", meetingtitle=").append(meetingtitle);
		sb.append(", credits=").append(credits);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", updatetime=").append(updatetime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}