package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;
import java.net.URLEncoder;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import com.kasite.core.common.config.KasiteConfig;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 企微消息推送 This class was generated by MyBatis Generator. This class corresponds
 * to the database table QY_MSG_PUSH
 */
@Table(name = "QY_MSG_PUSH")
public class MsgPush implements Serializable {
	/**
	 * 主键ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Integer id;

	/**
	 * 对应的业务ID
	 */
	@Column(name = "UID")
	private String uid;

	/**
	 * 消息标题
	 */
	@Column(name = "MSGTITLE")
	private String msgtitle;

	/**
	 * 消息描述
	 */
	@Column(name = "MSGCONTENT")
	private String msgcontent;

	/**
	 * 点击跳转地址
	 */
	@Column(name = "MSGURL")
	private String msgurl;

	/**
	 * 图片地址
	 */
	@Column(name = "PICURL")
	private String picurl;
	/**
	 * 成员ID列表（消息接收者，多个接收者用‘|’分隔，最多支持1000个）。特殊情况：指定为@all，则向关注该企业应用的全部成员发送
	 */
	@Column(name = "TOUSER")
	private String touser;

	/**
	 * 部门ID列表，多个接收者用‘|’分隔，最多支持100个。当touser为@all时忽略本参数
	 */
	@Column(name = "TOPARTY")
	private String toparty;

	/**
	 * 按钮文字。 默认为“详情”， 不超过4个文字，超过自动截断。
	 */
	@Column(name = "BTNTXT")
	private String btntxt;

	/**
	 * 消息类型 1=文本卡片消息 2=图文消息
	 */
	@Column(name = "MSGTYPE")
	private Integer msgtype;

	/**
	 * 发送结果
	 */
	@Column(name = "RESULT")
	private String result;

	/**
	 * 重试次数
	 */
	@Column(name = "RETRY")
	private int retry;

	/**
	 * 配置中心key
	 */
	@Column(name = "CONFIGKEY")
	private String configkey;

	/**
	 * 操作人ID
	 */
	@Column(name = "OPERATORID")
	private String operatorid;

	/**
	 * 操作人姓名
	 */
	@Column(name = "OPERATORNAME")
	private String operatorname;

	/**
	 * 插入时间
	 */
	@Column(name = "INSERTTIME")
	private Date inserttime;

	/**
	 * 修改时间
	 */
	@Column(name = "UPDATETIME")
	private Date updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_MSG_PUSH
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	public String getPicurl() {
		return picurl;
	}

	public void setPicurl(String picurl) {
		this.picurl = picurl;
	}

	public int getRetry() {
		return retry;
	}

	public void setRetry(int retry) {
		this.retry = retry;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.ID
	 *
	 * @return the value of QY_MSG_PUSH.ID
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.ID
	 *
	 * @param id the value for QY_MSG_PUSH.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.UID
	 *
	 * @return the value of QY_MSG_PUSH.UID
	 *
	 * @mbg.generated
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.UID
	 *
	 * @param uid the value for QY_MSG_PUSH.UID
	 *
	 * @mbg.generated
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.MSGTITLE
	 *
	 * @return the value of QY_MSG_PUSH.MSGTITLE
	 *
	 * @mbg.generated
	 */
	public String getMsgtitle() {
		return msgtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.MSGTITLE
	 *
	 * @param msgtitle the value for QY_MSG_PUSH.MSGTITLE
	 *
	 * @mbg.generated
	 */
	public void setMsgtitle(String msgtitle) {
		this.msgtitle = msgtitle == null ? null : msgtitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.MSGCONTENT
	 *
	 * @return the value of QY_MSG_PUSH.MSGCONTENT
	 *
	 * @mbg.generated
	 */
	public String getMsgcontent() {
		return msgcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.MSGCONTENT
	 *
	 * @param msgcontent the value for QY_MSG_PUSH.MSGCONTENT
	 *
	 * @mbg.generated
	 */
	public void setMsgcontent(String msgcontent) {
		this.msgcontent = msgcontent == null ? null : msgcontent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.MSGURL
	 *
	 * @return the value of QY_MSG_PUSH.MSGURL
	 *
	 * @mbg.generated
	 */
	public String getMsgurl() {
		return msgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.MSGURL
	 *
	 * @param msgurl the value for QY_MSG_PUSH.MSGURL
	 *
	 * @mbg.generated
	 */
	public void setMsgurl(String msgurl) {
		this.msgurl = msgurl == null ? null : msgurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.TOUSER
	 *
	 * @return the value of QY_MSG_PUSH.TOUSER
	 *
	 * @mbg.generated
	 */
	public String getTouser() {
		return touser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.TOUSER
	 *
	 * @param touser the value for QY_MSG_PUSH.TOUSER
	 *
	 * @mbg.generated
	 */
	public void setTouser(String touser) {
		this.touser = touser == null ? null : touser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.TOPARTY
	 *
	 * @return the value of QY_MSG_PUSH.TOPARTY
	 *
	 * @mbg.generated
	 */
	public String getToparty() {
		return toparty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.TOPARTY
	 *
	 * @param toparty the value for QY_MSG_PUSH.TOPARTY
	 *
	 * @mbg.generated
	 */
	public void setToparty(String toparty) {
		this.toparty = toparty == null ? null : toparty.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.BTNTXT
	 *
	 * @return the value of QY_MSG_PUSH.BTNTXT
	 *
	 * @mbg.generated
	 */
	public String getBtntxt() {
		return btntxt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.BTNTXT
	 *
	 * @param btntxt the value for QY_MSG_PUSH.BTNTXT
	 *
	 * @mbg.generated
	 */
	public void setBtntxt(String btntxt) {
		this.btntxt = btntxt == null ? null : btntxt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.MSGTYPE
	 *
	 * @return the value of QY_MSG_PUSH.MSGTYPE
	 *
	 * @mbg.generated
	 */
	public Integer getMsgtype() {
		return msgtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.MSGTYPE
	 *
	 * @param msgtype the value for QY_MSG_PUSH.MSGTYPE
	 *
	 * @mbg.generated
	 */
	public void setMsgtype(Integer msgtype) {
		this.msgtype = msgtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.CONFIGKEY
	 *
	 * @return the value of QY_MSG_PUSH.CONFIGKEY
	 *
	 * @mbg.generated
	 */
	public String getConfigkey() {
		return configkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.CONFIGKEY
	 *
	 * @param configkey the value for QY_MSG_PUSH.CONFIGKEY
	 *
	 * @mbg.generated
	 */
	public void setConfigkey(String configkey) {
		this.configkey = configkey == null ? null : configkey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.OPERATORID
	 *
	 * @return the value of QY_MSG_PUSH.OPERATORID
	 *
	 * @mbg.generated
	 */
	public String getOperatorid() {
		return operatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.OPERATORID
	 *
	 * @param operatorid the value for QY_MSG_PUSH.OPERATORID
	 *
	 * @mbg.generated
	 */
	public void setOperatorid(String operatorid) {
		this.operatorid = operatorid == null ? null : operatorid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.OPERATORNAME
	 *
	 * @return the value of QY_MSG_PUSH.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public String getOperatorname() {
		return operatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.OPERATORNAME
	 *
	 * @param operatorname the value for QY_MSG_PUSH.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public void setOperatorname(String operatorname) {
		this.operatorname = operatorname == null ? null : operatorname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.INSERTTIME
	 *
	 * @return the value of QY_MSG_PUSH.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public Date getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.INSERTTIME
	 *
	 * @param inserttime the value for QY_MSG_PUSH.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(Date inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MSG_PUSH.UPDATETIME
	 *
	 * @return the value of QY_MSG_PUSH.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MSG_PUSH.UPDATETIME
	 *
	 * @param updatetime the value for QY_MSG_PUSH.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_MSG_PUSH
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", uid=").append(uid);
		sb.append(", msgtitle=").append(msgtitle);
		sb.append(", msgcontent=").append(msgcontent);
		sb.append(", msgurl=").append(msgurl);
		sb.append(", touser=").append(touser);
		sb.append(", toparty=").append(toparty);
		sb.append(", btntxt=").append(btntxt);
		sb.append(", msgtype=").append(msgtype);
		sb.append(", configkey=").append(configkey);
		sb.append(", operatorid=").append(operatorid);
		sb.append(", operatorname=").append(operatorname);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", updatetime=").append(updatetime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	public void setMsgPush(String touser, String toparty, String uid, String title, String msgContent, String toUrl,
			String configKey, String clientId, String picUrl, int msgType) throws Exception {
		this.touser = touser;
		this.toparty = toparty;
		this.uid = uid;
		this.msgtitle = title;
		this.msgcontent = msgContent;
		StringBuffer msgUrl = new StringBuffer();
		String mainUrl = KasiteConfig.getKasiteHosWebAppUrl();
		msgUrl.append(KasiteConfig.getKasiteHosWebAppUrl()).append("/qywechat/").append(clientId).append("/")
				.append(configKey).append("/gotoOauth.do?toUrl=").append(URLEncoder.encode(mainUrl + toUrl, "utf-8"));
		this.msgurl = msgUrl.toString();
		this.picurl = picUrl;
		this.msgtype = msgType;
		this.configkey = configKey;
		this.operatorid = "system";
		this.operatorname = "system";
	}
}