package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 问题-答案 This class was generated by MyBatis Generator. This class corresponds
 * to the database table QY_QUESTION_ANSWER
 */
@Table(name = "QY_QUESTION_ANSWER")
public class QuestionAnswer implements Serializable {
	/**
	 * 主键 选项ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Integer id;

	/**
	 * 投票、问卷UID
	 */
	@Column(name = "THEMEID")
	private String themeid;

	/**
	 * 问题ID
	 */
	@Column(name = "QUESTID")
	private Integer questid;

	/**
	 * 答案
	 */
	@Column(name = "ANSWER")
	private String answer;

	/**
	 * 其他答案
	 */
	@Column(name = "OTHERANSWER")
	private String otheranswer;

	/**
	 * 操作人ID
	 */
	@Column(name = "OPERATORID")
	private String operatorid;

	/**
	 * 操作人姓名
	 */
	@Column(name = "OPERATORNAME")
	private String operatorname;

	/**
	 * 插入时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * 修改时间
	 */
	@Column(name = "UPDATETIME")
	private String updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_QUESTION_ANSWER
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION_ANSWER.ID
	 *
	 * @return the value of QY_QUESTION_ANSWER.ID
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION_ANSWER.ID
	 *
	 * @param id the value for QY_QUESTION_ANSWER.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION_ANSWER.SAMPLEID
	 *
	 * @return the value of QY_QUESTION_ANSWER.SAMPLEID
	 *
	 * @mbg.generated
	 */
	public String getThemeid() {
		return themeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION_ANSWER.SAMPLEID
	 *
	 * @param sampleid the value for QY_QUESTION_ANSWER.SAMPLEID
	 *
	 * @mbg.generated
	 */
	public void setThemeid(String themeid) {
		this.themeid = themeid == null ? null : themeid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION_ANSWER.QUESTID
	 *
	 * @return the value of QY_QUESTION_ANSWER.QUESTID
	 *
	 * @mbg.generated
	 */
	public Integer getQuestid() {
		return questid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION_ANSWER.QUESTID
	 *
	 * @param questid the value for QY_QUESTION_ANSWER.QUESTID
	 *
	 * @mbg.generated
	 */
	public void setQuestid(Integer questid) {
		this.questid = questid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION_ANSWER.ANSWER
	 *
	 * @return the value of QY_QUESTION_ANSWER.ANSWER
	 *
	 * @mbg.generated
	 */
	public String getAnswer() {
		return answer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION_ANSWER.ANSWER
	 *
	 * @param answer the value for QY_QUESTION_ANSWER.ANSWER
	 *
	 * @mbg.generated
	 */
	public void setAnswer(String answer) {
		this.answer = answer == null ? null : answer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION_ANSWER.OTHERANSWER
	 *
	 * @return the value of QY_QUESTION_ANSWER.OTHERANSWER
	 *
	 * @mbg.generated
	 */
	public String getOtheranswer() {
		return otheranswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION_ANSWER.OTHERANSWER
	 *
	 * @param otheranswer the value for QY_QUESTION_ANSWER.OTHERANSWER
	 *
	 * @mbg.generated
	 */
	public void setOtheranswer(String otheranswer) {
		this.otheranswer = otheranswer == null ? null : otheranswer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION_ANSWER.OPERATORID
	 *
	 * @return the value of QY_QUESTION_ANSWER.OPERATORID
	 *
	 * @mbg.generated
	 */
	public String getOperatorid() {
		return operatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION_ANSWER.OPERATORID
	 *
	 * @param operatorid the value for QY_QUESTION_ANSWER.OPERATORID
	 *
	 * @mbg.generated
	 */
	public void setOperatorid(String operatorid) {
		this.operatorid = operatorid == null ? null : operatorid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION_ANSWER.OPERATORNAME
	 *
	 * @return the value of QY_QUESTION_ANSWER.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public String getOperatorname() {
		return operatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION_ANSWER.OPERATORNAME
	 *
	 * @param operatorname the value for QY_QUESTION_ANSWER.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public void setOperatorname(String operatorname) {
		this.operatorname = operatorname == null ? null : operatorname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION_ANSWER.INSERTTIME
	 *
	 * @return the value of QY_QUESTION_ANSWER.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION_ANSWER.INSERTTIME
	 *
	 * @param inserttime the value for QY_QUESTION_ANSWER.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION_ANSWER.UPDATETIME
	 *
	 * @return the value of QY_QUESTION_ANSWER.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION_ANSWER.UPDATETIME
	 *
	 * @param updatetime the value for QY_QUESTION_ANSWER.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_QUESTION_ANSWER
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", sampleid=").append(themeid);
		sb.append(", questid=").append(questid);
		sb.append(", answer=").append(answer);
		sb.append(", otheranswer=").append(otheranswer);
		sb.append(", operatorid=").append(operatorid);
		sb.append(", operatorname=").append(operatorname);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", updatetime=").append(updatetime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}