
package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 问题选项 This class was generated by MyBatis Generator. This class corresponds to
 * the database table QY_QUESTIONITEM
 */
@Table(name = "QY_QUESTION_ITEM")
public class QuestionItem implements Serializable {
	/**
	 * 主键 选项ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	/**
	 * 投票或问卷主题UID
	 */
	@Column(name = "THEMEID")
	private String themeid;

	/**
	 * 问题ID
	 */
	@Column(name = "QUESTID")
	private Integer questid;

	/**
	 * 选项值
	 */
	@Column(name = "ITEMVALUE")
	private String itemvalue;

	/**
	 * 排序编号
	 */
	@Column(name = "SORTNUM")
	private Integer sortnum;

	/**
	 * 状态 默认0=有效 1=无效
	 */
	@Column(name = "STATUS")
	private Integer status;

	/**
	 * 操作人ID
	 */
	@Column(name = "OPERATORID")
	private String operatorid;

	/**
	 * 操作人姓名
	 */
	@Column(name = "OPERATORNAME")
	private String operatorname;

	/**
	 * 插入时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * 修改时间
	 */
	@Column(name = "UPDATETIME")
	private String updatetime;

	public String getThemeid() {
		return themeid;
	}

	public void setThemeid(String themeid) {
		this.themeid = themeid;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_QUESTIONITEM
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTIONITEM.ID
	 *
	 * @return the value of QY_QUESTIONITEM.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTIONITEM.ID
	 *
	 * @param id the value for QY_QUESTIONITEM.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTIONITEM.QUESTID
	 *
	 * @return the value of QY_QUESTIONITEM.QUESTID
	 *
	 * @mbg.generated
	 */
	public Integer getQuestid() {
		return questid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTIONITEM.QUESTID
	 *
	 * @param questid the value for QY_QUESTIONITEM.QUESTID
	 *
	 * @mbg.generated
	 */
	public void setQuestid(Integer questid) {
		this.questid = questid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTIONITEM.ITEMVALUE
	 *
	 * @return the value of QY_QUESTIONITEM.ITEMVALUE
	 *
	 * @mbg.generated
	 */
	public String getItemvalue() {
		return itemvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTIONITEM.ITEMVALUE
	 *
	 * @param itemvalue the value for QY_QUESTIONITEM.ITEMVALUE
	 *
	 * @mbg.generated
	 */
	public void setItemvalue(String itemvalue) {
		this.itemvalue = itemvalue == null ? null : itemvalue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTIONITEM.SORTNUM
	 *
	 * @return the value of QY_QUESTIONITEM.SORTNUM
	 *
	 * @mbg.generated
	 */
	public Integer getSortnum() {
		return sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTIONITEM.SORTNUM
	 *
	 * @param sortnum the value for QY_QUESTIONITEM.SORTNUM
	 *
	 * @mbg.generated
	 */
	public void setSortnum(Integer sortnum) {
		this.sortnum = sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTIONITEM.STATUS
	 *
	 * @return the value of QY_QUESTIONITEM.STATUS
	 *
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTIONITEM.STATUS
	 *
	 * @param status the value for QY_QUESTIONITEM.STATUS
	 *
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTIONITEM.OPERATORID
	 *
	 * @return the value of QY_QUESTIONITEM.OPERATORID
	 *
	 * @mbg.generated
	 */
	public String getOperatorid() {
		return operatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTIONITEM.OPERATORID
	 *
	 * @param operatorid the value for QY_QUESTIONITEM.OPERATORID
	 *
	 * @mbg.generated
	 */
	public void setOperatorid(String operatorid) {
		this.operatorid = operatorid == null ? null : operatorid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTIONITEM.OPERATORNAME
	 *
	 * @return the value of QY_QUESTIONITEM.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public String getOperatorname() {
		return operatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTIONITEM.OPERATORNAME
	 *
	 * @param operatorname the value for QY_QUESTIONITEM.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public void setOperatorname(String operatorname) {
		this.operatorname = operatorname == null ? null : operatorname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTIONITEM.INSERTTIME
	 *
	 * @return the value of QY_QUESTIONITEM.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTIONITEM.INSERTTIME
	 *
	 * @param inserttime the value for QY_QUESTIONITEM.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTIONITEM.UPDATETIME
	 *
	 * @return the value of QY_QUESTIONITEM.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTIONITEM.UPDATETIME
	 *
	 * @param updatetime the value for QY_QUESTIONITEM.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_QUESTIONITEM
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", questid=").append(questid);
		sb.append(", itemvalue=").append(itemvalue);
		sb.append(", sortnum=").append(sortnum);
		sb.append(", status=").append(status);
		sb.append(", operatorid=").append(operatorid);
		sb.append(", operatorname=").append(operatorname);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", updatetime=").append(updatetime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}