package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 问题 This class was generated by MyBatis Generator. This class corresponds to
 * the database table QY_QUESTION
 */
@Table(name = "QY_QUESTION")
public class Question implements Serializable {
	/**
	 * 主键 问题ID
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	/**
	 * 投票或问卷主题ID
	 */
	@Column(name = "THEMEID")
	private String themeid;

	/**
	 * 问题名称
	 */
	@Column(name = "QUESTNAME")
	private String questname;

	/**
	 * 问题类型 0=单选 1=多选 2=问答 3=打分
	 */
	@Column(name = "QUESTTYPE")
	private Integer questtype;

	/**
	 * 排序编号
	 */
	@Column(name = "SORTNUM")
	private Integer sortnum;

	/**
	 * 状态 0=有效 1=无效
	 */
	@Column(name = "STATUS")
	private Integer status;

	/**
	 * 该题是否必答 默认0=是 1=否
	 */
	@Column(name = "ISMUST")
	private Integer ismust;

	/**
	 * 操作人ID
	 */
	@Column(name = "OPERATORID")
	private String operatorid;

	/**
	 * 操作人姓名
	 */
	@Column(name = "OPERATORNAME")
	private String operatorname;

	/**
	 * 插入时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * 修改时间
	 */
	@Column(name = "UPDATETIME")
	private String updatetime;

	public String getQuestname() {
		return questname;
	}

	public void setQuestname(String questname) {
		this.questname = questname;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_QUESTION
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.ID
	 *
	 * @return the value of QY_QUESTION.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.ID
	 *
	 * @param id the value for QY_QUESTION.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.THEMEID
	 *
	 * @return the value of QY_QUESTION.THEMEID
	 *
	 * @mbg.generated
	 */
	public String getThemeid() {
		return themeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.THEMEID
	 *
	 * @param themeid the value for QY_QUESTION.THEMEID
	 *
	 * @mbg.generated
	 */
	public void setThemeid(String themeid) {
		this.themeid = themeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.QUESTTYPE
	 *
	 * @return the value of QY_QUESTION.QUESTTYPE
	 *
	 * @mbg.generated
	 */
	public Integer getQuesttype() {
		return questtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.QUESTTYPE
	 *
	 * @param questtype the value for QY_QUESTION.QUESTTYPE
	 *
	 * @mbg.generated
	 */
	public void setQuesttype(Integer questtype) {
		this.questtype = questtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.SORTNUM
	 *
	 * @return the value of QY_QUESTION.SORTNUM
	 *
	 * @mbg.generated
	 */
	public Integer getSortnum() {
		return sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.SORTNUM
	 *
	 * @param sortnum the value for QY_QUESTION.SORTNUM
	 *
	 * @mbg.generated
	 */
	public void setSortnum(Integer sortnum) {
		this.sortnum = sortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.STATUS
	 *
	 * @return the value of QY_QUESTION.STATUS
	 *
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.STATUS
	 *
	 * @param status the value for QY_QUESTION.STATUS
	 *
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.ISMUST
	 *
	 * @return the value of QY_QUESTION.ISMUST
	 *
	 * @mbg.generated
	 */
	public Integer getIsmust() {
		return ismust;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.ISMUST
	 *
	 * @param ismust the value for QY_QUESTION.ISMUST
	 *
	 * @mbg.generated
	 */
	public void setIsmust(Integer ismust) {
		this.ismust = ismust;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.OPERATORID
	 *
	 * @return the value of QY_QUESTION.OPERATORID
	 *
	 * @mbg.generated
	 */
	public String getOperatorid() {
		return operatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.OPERATORID
	 *
	 * @param operatorid the value for QY_QUESTION.OPERATORID
	 *
	 * @mbg.generated
	 */
	public void setOperatorid(String operatorid) {
		this.operatorid = operatorid == null ? null : operatorid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.OPERATORNAME
	 *
	 * @return the value of QY_QUESTION.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public String getOperatorname() {
		return operatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.OPERATORNAME
	 *
	 * @param operatorname the value for QY_QUESTION.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public void setOperatorname(String operatorname) {
		this.operatorname = operatorname == null ? null : operatorname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.INSERTTIME
	 *
	 * @return the value of QY_QUESTION.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.INSERTTIME
	 *
	 * @param inserttime the value for QY_QUESTION.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_QUESTION.UPDATETIME
	 *
	 * @return the value of QY_QUESTION.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_QUESTION.UPDATETIME
	 *
	 * @param updatetime the value for QY_QUESTION.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_QUESTION
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", themeid=").append(themeid);
		sb.append(", questtype=").append(questtype);
		sb.append(", sortnum=").append(sortnum);
		sb.append(", status=").append(status);
		sb.append(", ismust=").append(ismust);
		sb.append(", operatorid=").append(operatorid);
		sb.append(", operatorname=").append(operatorname);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", updatetime=").append(updatetime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}