package com.kasite.core.serviceinterface.module.qywechat.dbo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

import tk.mybatis.mapper.annotation.KeySql;

/**
 * 参与人 This class was generated by MyBatis Generator. This class corresponds to
 * the database table QY_TO_MEMBER
 */
@Table(name = "QY_TO_MEMBER")
public class ToMember implements Serializable {
	/**
	 */
	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	/**
	 * 成员对应的订单ID、会议ID等
	 */
	@Column(name = "UID")
	private String uid;

	/**
	 * 人员ID、或者部门ID
	 */
	@Column(name = "MEMBERID")
	private String memberid;

	/**
	 * 是否部门 默认0=否 1=是
	 */
	@Column(name = "ISDEPT")
	private int isDept;

	/**
	 * 人员名称、或者部门名称
	 */
	@Column(name = "MEMBERNAME")
	private String membername;

	/**
	 * 类型 0=参与人 1=会议记录人 2=参加（报名） 3=请假 4=维修人 5=可见人员
	 */
	@Column(name = "MEMBERTYPE")
	private Integer membertype;

//    /**
//     *   状态 默认=0无状态\待定  1=参加（报名） 2=请假 
//     */
//    @Column(name = "STATUS")
//    private Integer status;

	/**
	 * 创建时间
	 */
	@Column(name = "INSERTTIME")
	private String inserttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_TO_MEMBER
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	public int getIsDept() {
		return isDept;
	}

	public void setIsDept(int isDept) {
		this.isDept = isDept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_TO_MEMBER.ID
	 *
	 * @return the value of QY_TO_MEMBER.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_TO_MEMBER.ID
	 *
	 * @param id the value for QY_TO_MEMBER.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_TO_MEMBER.UID
	 *
	 * @return the value of QY_TO_MEMBER.UID
	 *
	 * @mbg.generated
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_TO_MEMBER.UID
	 *
	 * @param uid the value for QY_TO_MEMBER.UID
	 *
	 * @mbg.generated
	 */
	public void setUid(String uid) {
		this.uid = uid == null ? null : uid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_TO_MEMBER.MEMBERID
	 *
	 * @return the value of QY_TO_MEMBER.MEMBERID
	 *
	 * @mbg.generated
	 */
	public String getMemberid() {
		return memberid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_TO_MEMBER.MEMBERID
	 *
	 * @param memberid the value for QY_TO_MEMBER.MEMBERID
	 *
	 * @mbg.generated
	 */
	public void setMemberid(String memberid) {
		this.memberid = memberid == null ? null : memberid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_TO_MEMBER.MEMBERNAME
	 *
	 * @return the value of QY_TO_MEMBER.MEMBERNAME
	 *
	 * @mbg.generated
	 */
	public String getMembername() {
		return membername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_TO_MEMBER.MEMBERNAME
	 *
	 * @param membername the value for QY_TO_MEMBER.MEMBERNAME
	 *
	 * @mbg.generated
	 */
	public void setMembername(String membername) {
		this.membername = membername == null ? null : membername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_TO_MEMBER.MEMBERTYPE
	 *
	 * @return the value of QY_TO_MEMBER.MEMBERTYPE
	 *
	 * @mbg.generated
	 */
	public Integer getMembertype() {
		return membertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_TO_MEMBER.MEMBERTYPE
	 *
	 * @param membertype the value for QY_TO_MEMBER.MEMBERTYPE
	 *
	 * @mbg.generated
	 */
	public void setMembertype(Integer membertype) {
		this.membertype = membertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_TO_MEMBER.STATUS
	 *
	 * @return the value of QY_TO_MEMBER.STATUS
	 *
	 * @mbg.generated
	 */
//    public Integer getStatus() {
//        return status;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column QY_TO_MEMBER.STATUS
//     *
//     * @param status the value for QY_TO_MEMBER.STATUS
//     *
//     * @mbg.generated
//     */
//    public void setStatus(Integer status) {
//        this.status = status;
//    }

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_TO_MEMBER.INSERTTIME
	 *
	 * @return the value of QY_TO_MEMBER.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_TO_MEMBER.INSERTTIME
	 *
	 * @param inserttime the value for QY_TO_MEMBER.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table QY_TO_MEMBER
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", uid=").append(uid);
		sb.append(", memberid=").append(memberid);
		sb.append(", membername=").append(membername);
		sb.append(", membertype=").append(membertype);
		// sb.append(", status=").append(status);
		sb.append(", inserttime=").append(inserttime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}