package com.kasite.core.serviceinterface.module.qywechat.resp;

import com.kasite.core.common.resp.AbsResp;

/**
 * 成员RESP
 * 
 * @author 無
 *
 */
public class RespMember extends AbsResp {

	/**
	 * 主键ID
	 */
	private Long id;

	/**
	 * 成员ID
	 */
	private String memberid;

	/**
	 * 成员名称
	 */
	private String membername;

	/**
	 * 插入时间
	 */
	private String inserttime;

	/**
	 * 修改时间
	 */
	private String updatetime;

	/**
	 * 总学分
	 */
	private Integer allCredits;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS.ID
	 *
	 * @return the value of QY_MEMBER_CREDITS.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS.ID
	 *
	 * @param id the value for QY_MEMBER_CREDITS.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS.MEMBERID
	 *
	 * @return the value of QY_MEMBER_CREDITS.MEMBERID
	 *
	 * @mbg.generated
	 */
	public String getMemberid() {
		return memberid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS.MEMBERID
	 *
	 * @param memberid the value for QY_MEMBER_CREDITS.MEMBERID
	 *
	 * @mbg.generated
	 */
	public void setMemberid(String memberid) {
		this.memberid = memberid == null ? null : memberid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS.MEMBERNAME
	 *
	 * @return the value of QY_MEMBER_CREDITS.MEMBERNAME
	 *
	 * @mbg.generated
	 */
	public String getMembername() {
		return membername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS.MEMBERNAME
	 *
	 * @param membername the value for QY_MEMBER_CREDITS.MEMBERNAME
	 *
	 * @mbg.generated
	 */
	public void setMembername(String membername) {
		this.membername = membername == null ? null : membername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS.INSERTTIME
	 *
	 * @return the value of QY_MEMBER_CREDITS.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS.INSERTTIME
	 *
	 * @param inserttime the value for QY_MEMBER_CREDITS.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEMBER_CREDITS.UPDATETIME
	 *
	 * @return the value of QY_MEMBER_CREDITS.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEMBER_CREDITS.UPDATETIME
	 *
	 * @param updatetime the value for QY_MEMBER_CREDITS.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	public Integer getAllCredits() {
		return allCredits;
	}

	public void setAllCredits(Integer allCredits) {
		this.allCredits = allCredits;
	}

}
