package com.kasite.core.serviceinterface.module.qywechat.resp;

import com.kasite.core.common.resp.AbsResp;

/**
 * 活动邀请RESP
 * 
 * @author 無
 *
 */
public class RespActivity extends AbsResp {
	/**
	 * 主键
	 */
	private Long id;

	/**
	 * 主题
	 */
	private String title;

	/**
	 * uuid
	 */
	private String activityid;

	/**
	 * 报名截止时间
	 */
	private String expiretime;

	/**
	 * 活动开始时间
	 */
	private String starttime;

	/**
	 * 活动结束时间
	 */
	private String endtime;

	/**
	 * 报名人数 默认0=不限制人数 N=N个人
	 */
	private Integer totalnumber;

	/**
	 * 活动地点
	 */
	private String place;

	/**
	 * 状态 0=未开始 1=报名中 2=已结束
	 */
	private Integer status;

	/**
	 * 发起人ID
	 */
	private String operatorid;

	/**
	 * 发起人姓名
	 */
	private String operatorname;

	/**
	 * 插入时间
	 */
	private String inserttime;

	/**
	 * 修改时间
	 */
	private String updatetime;

	/**
	 * 简介
	 */
	private String intro;

	/**
	 * 阅读数
	 */
	private Integer readNumber;

	/**
	 * 报名人数
	 */
	private Integer partNumber;

	/**
	 * 图片URL
	 */
	private String imgUrl;

	/**
	 * 图片名
	 */
	private String imgName;

	/**
	 * 附件RUL
	 */
	private String attachmentUrl;

	/**
	 * 附件名
	 */
	private String attachmentName;
	
	/**
	 * 登录人姓名
	 */
	private String loginMemberName;
	
	
	private String qrPicUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table QY_ACTIVITY
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.ID
	 *
	 * @return the value of QY_ACTIVITY.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.ID
	 *
	 * @param id the value for QY_ACTIVITY.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.TITLE
	 *
	 * @return the value of QY_ACTIVITY.TITLE
	 *
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.TITLE
	 *
	 * @param title the value for QY_ACTIVITY.TITLE
	 *
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.EXPIRETIME
	 *
	 * @return the value of QY_ACTIVITY.EXPIRETIME
	 *
	 * @mbg.generated
	 */
	public String getExpiretime() {
		return expiretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.EXPIRETIME
	 *
	 * @param expiretime the value for QY_ACTIVITY.EXPIRETIME
	 *
	 * @mbg.generated
	 */
	public void setExpiretime(String expiretime) {
		this.expiretime = expiretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.STARTTIME
	 *
	 * @return the value of QY_ACTIVITY.STARTTIME
	 *
	 * @mbg.generated
	 */
	public String getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.STARTTIME
	 *
	 * @param starttime the value for QY_ACTIVITY.STARTTIME
	 *
	 * @mbg.generated
	 */
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.ENDTIME
	 *
	 * @return the value of QY_ACTIVITY.ENDTIME
	 *
	 * @mbg.generated
	 */
	public String getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.ENDTIME
	 *
	 * @param endtime the value for QY_ACTIVITY.ENDTIME
	 *
	 * @mbg.generated
	 */
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.TOTALNUMBER
	 *
	 * @return the value of QY_ACTIVITY.TOTALNUMBER
	 *
	 * @mbg.generated
	 */
	public Integer getTotalnumber() {
		return totalnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.TOTALNUMBER
	 *
	 * @param totalnumber the value for QY_ACTIVITY.TOTALNUMBER
	 *
	 * @mbg.generated
	 */
	public void setTotalnumber(Integer totalnumber) {
		this.totalnumber = totalnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.PLACE
	 *
	 * @return the value of QY_ACTIVITY.PLACE
	 *
	 * @mbg.generated
	 */
	public String getPlace() {
		return place;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.PLACE
	 *
	 * @param place the value for QY_ACTIVITY.PLACE
	 *
	 * @mbg.generated
	 */
	public void setPlace(String place) {
		this.place = place == null ? null : place.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.STATUS
	 *
	 * @return the value of QY_ACTIVITY.STATUS
	 *
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.STATUS
	 *
	 * @param status the value for QY_ACTIVITY.STATUS
	 *
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.OPERATORID
	 *
	 * @return the value of QY_ACTIVITY.OPERATORID
	 *
	 * @mbg.generated
	 */
	public String getOperatorid() {
		return operatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.OPERATORID
	 *
	 * @param operatorid the value for QY_ACTIVITY.OPERATORID
	 *
	 * @mbg.generated
	 */
	public void setOperatorid(String operatorid) {
		this.operatorid = operatorid == null ? null : operatorid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.OPERATORNAME
	 *
	 * @return the value of QY_ACTIVITY.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public String getOperatorname() {
		return operatorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.OPERATORNAME
	 *
	 * @param operatorname the value for QY_ACTIVITY.OPERATORNAME
	 *
	 * @mbg.generated
	 */
	public void setOperatorname(String operatorname) {
		this.operatorname = operatorname == null ? null : operatorname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.INSERTTIME
	 *
	 * @return the value of QY_ACTIVITY.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.INSERTTIME
	 *
	 * @param inserttime the value for QY_ACTIVITY.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.UPDATETIME
	 *
	 * @return the value of QY_ACTIVITY.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.UPDATETIME
	 *
	 * @param updatetime the value for QY_ACTIVITY.UPDATETIME
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_ACTIVITY.INTRO
	 *
	 * @return the value of QY_ACTIVITY.INTRO
	 *
	 * @mbg.generated
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_ACTIVITY.INTRO
	 *
	 * @param intro the value for QY_ACTIVITY.INTRO
	 *
	 * @mbg.generated
	 */
	public void setIntro(String intro) {
		this.intro = intro == null ? null : intro.trim();
	}

	public String getActivityid() {
		return activityid;
	}

	public void setActivityid(String activityid) {
		this.activityid = activityid;
	}

	public Integer getReadNumber() {
		return readNumber;
	}

	public void setReadNumber(Integer readNumber) {
		this.readNumber = readNumber;
	}

	public Integer getPartNumber() {
		return partNumber;
	}

	public void setPartNumber(Integer partNumber) {
		this.partNumber = partNumber;
	}

	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getImgName() {
		return imgName;
	}

	public void setImgName(String imgName) {
		this.imgName = imgName;
	}

	public String getAttachmentUrl() {
		return attachmentUrl;
	}

	public void setAttachmentUrl(String attachmentUrl) {
		this.attachmentUrl = attachmentUrl;
	}

	public String getAttachmentName() {
		return attachmentName;
	}

	public void setAttachmentName(String attachmentName) {
		this.attachmentName = attachmentName;
	}

	public String getQrPicUrl() {
		return qrPicUrl;
	}

	public void setQrPicUrl(String qrPicUrl) {
		this.qrPicUrl = qrPicUrl;
	}

	public String getLoginMemberName() {
		return loginMemberName;
	}

	public void setLoginMemberName(String loginMemberName) {
		this.loginMemberName = loginMemberName;
	}

}
