package com.kasite.core.serviceinterface.module.qywechat.req;

import org.dom4j.Element;

import com.kasite.core.common.constant.KstHosConstant;
import com.kasite.core.common.req.AbsReq;
import com.kasite.core.common.util.XMLUtil;
import com.yihu.hos.exception.AbsHosException;
import com.yihu.wsgw.api.InterfaceMessage;

/**
 * 会议签到、签退req
 * 
 * @author 無
 *
 */
public class ReqMeetingSign extends AbsReq {
	/**
	 * 主键ID
	 */
	private Long id;

	/**
	 * 附件对应的订单ID、会议ID等
	 */
	private String uid;

	/**
	 * 纬度
	 */
	private String latitude;

	/**
	 * 维度
	 */
	private String longitude;

	/**
	 * 位置精度
	 */
	private String accuracy;

	/**
	 * 签到、签退地点名称
	 */
	private String place;

	/**
	 * 签到人ID
	 */
	private String memberid;

	/**
	 * 签到人姓名
	 */
	private String membername;

	/**
	 * 签到、签退时间
	 */
	private String inserttime;

	/**
	 * 类型 0=签到 1=签退
	 */
	private Integer signtype;

	/**
	 * 查询条件 - 参会情况
	 */
	private String gotoMeeting;

	/**
	 * 查询条件 - 签到情况
	 */
	private String signIn;

	/**
	 * 查询条件 - 签退情况
	 */
	private String signBack;

	/**
	 * 参会情况
	 */
	private String memberType;

	public ReqMeetingSign(InterfaceMessage msg) throws AbsHosException {
		super(msg);
		Element ser = root.element(KstHosConstant.DATA);
		this.id = XMLUtil.getLong(ser, "id", false);
		this.uid = XMLUtil.getString(ser, "uid", false);
		this.latitude = XMLUtil.getString(ser, "latitude", false);
		this.longitude = XMLUtil.getString(ser, "longitude", false);
		this.accuracy = XMLUtil.getString(ser, "accuracy", false);
		this.place = XMLUtil.getString(ser, "place", false);
		this.memberid = XMLUtil.getString(ser, "memberId", false);
		this.membername = XMLUtil.getString(ser, "memberName", false);
		this.signtype = XMLUtil.getInt(ser, "signType", false);
		this.inserttime = XMLUtil.getString(ser, "insertTime", false);

		// this.gotoMeeting = XMLUtil.getString(ser, "gotoMeeting", false);
		this.signIn = XMLUtil.getString(ser, "signIn", false);
		this.signBack = XMLUtil.getString(ser, "signBack", false);
		this.memberType = XMLUtil.getString(ser, "memberType", false);

	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.ID
	 *
	 * @return the value of QY_MEETING_SIGN.ID
	 *
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.ID
	 *
	 * @param id the value for QY_MEETING_SIGN.ID
	 *
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.UID
	 *
	 * @return the value of QY_MEETING_SIGN.UID
	 *
	 * @mbg.generated
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.UID
	 *
	 * @param uid the value for QY_MEETING_SIGN.UID
	 *
	 * @mbg.generated
	 */
	public void setUid(String uid) {
		this.uid = uid == null ? null : uid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.LATITUDE
	 *
	 * @return the value of QY_MEETING_SIGN.LATITUDE
	 *
	 * @mbg.generated
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.LATITUDE
	 *
	 * @param latitude the value for QY_MEETING_SIGN.LATITUDE
	 *
	 * @mbg.generated
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude == null ? null : latitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.LONGITUDE
	 *
	 * @return the value of QY_MEETING_SIGN.LONGITUDE
	 *
	 * @mbg.generated
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.LONGITUDE
	 *
	 * @param longitude the value for QY_MEETING_SIGN.LONGITUDE
	 *
	 * @mbg.generated
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude == null ? null : longitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.ACCURACY
	 *
	 * @return the value of QY_MEETING_SIGN.ACCURACY
	 *
	 * @mbg.generated
	 */
	public String getAccuracy() {
		return accuracy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.ACCURACY
	 *
	 * @param accuracy the value for QY_MEETING_SIGN.ACCURACY
	 *
	 * @mbg.generated
	 */
	public void setAccuracy(String accuracy) {
		this.accuracy = accuracy == null ? null : accuracy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.PLACE
	 *
	 * @return the value of QY_MEETING_SIGN.PLACE
	 *
	 * @mbg.generated
	 */
	public String getPlace() {
		return place;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.PLACE
	 *
	 * @param place the value for QY_MEETING_SIGN.PLACE
	 *
	 * @mbg.generated
	 */
	public void setPlace(String place) {
		this.place = place == null ? null : place.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.MEMBERID
	 *
	 * @return the value of QY_MEETING_SIGN.MEMBERID
	 *
	 * @mbg.generated
	 */
	public String getMemberid() {
		return memberid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.MEMBERID
	 *
	 * @param string the value for QY_MEETING_SIGN.MEMBERID
	 *
	 * @mbg.generated
	 */
	public void setMemberid(String string) {
		this.memberid = string;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.MEMBERNAME
	 *
	 * @return the value of QY_MEETING_SIGN.MEMBERNAME
	 *
	 * @mbg.generated
	 */
	public String getMembername() {
		return membername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.MEMBERNAME
	 *
	 * @param membername the value for QY_MEETING_SIGN.MEMBERNAME
	 *
	 * @mbg.generated
	 */
	public void setMembername(String membername) {
		this.membername = membername == null ? null : membername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.INSERTTIME
	 *
	 * @return the value of QY_MEETING_SIGN.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public String getInserttime() {
		return inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.INSERTTIME
	 *
	 * @param inserttime the value for QY_MEETING_SIGN.INSERTTIME
	 *
	 * @mbg.generated
	 */
	public void setInserttime(String inserttime) {
		this.inserttime = inserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column QY_MEETING_SIGN.SIGNTYPE
	 *
	 * @return the value of QY_MEETING_SIGN.SIGNTYPE
	 *
	 * @mbg.generated
	 */
	public Integer getSigntype() {
		return signtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column QY_MEETING_SIGN.SIGNTYPE
	 *
	 * @param signtype the value for QY_MEETING_SIGN.SIGNTYPE
	 *
	 * @mbg.generated
	 */
	public void setSigntype(Integer signtype) {
		this.signtype = signtype;
	}

	public String getGotoMeeting() {
		return gotoMeeting;
	}

	public void setGotoMeeting(String gotoMeeting) {
		this.gotoMeeting = gotoMeeting;
	}

	public String getSignIn() {
		return signIn;
	}

	public void setSignIn(String signIn) {
		this.signIn = signIn;
	}

	public String getSignBack() {
		return signBack;
	}

	public void setSignBack(String signBack) {
		this.signBack = signBack;
	}

//	public String getMeetingId() {
//		return meetingId;
//	}
//
//	public void setMeetingId(String meetingId) {
//		this.meetingId = meetingId;
//	}

	public String getMemberType() {
		return memberType;
	}

	public void setMemberType(String memberType) {
		this.memberType = memberType;
	}

}
