package com.kasite.core.serviceinterface.module.qywechat.req;

import org.dom4j.Element;

import com.kasite.core.common.constant.KstHosConstant;
import com.kasite.core.common.req.AbsReq;
import com.kasite.core.common.util.XMLUtil;
import com.yihu.hos.exception.AbsHosException;
import com.yihu.wsgw.api.InterfaceMessage;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table QY_QUESTION_ANSWER
 */
public class ReqQuestionAnswerQuery extends AbsReq {

	public ReqQuestionAnswerQuery(InterfaceMessage msg) throws AbsHosException {
		super(msg);
		Element ser = root.element(KstHosConstant.DATA);
		this.themeid = XMLUtil.getString(ser, "themeid", false);
		this.questid = XMLUtil.getInt(ser, "questid", false);
	}

	/**
	 * 投票、问卷UID
	 */
	private String themeid;

	/**
	 * 问题ID
	 */
	private Integer questid;

	public String getThemeid() {
		return themeid;
	}

	public void setThemeid(String themeid) {
		this.themeid = themeid;
	}

	public Integer getQuestid() {
		return questid;
	}

	public void setQuestid(Integer questid) {
		this.questid = questid;
	}

}