#卡斯特配置中心连接配置。默认是不开启，读取本地配置文件 数据采集子系统
kasite:
     #是否开启中心连接
    isConnectionKastieCenter: true
    #配置中心地址 如果不开启连接中心的时候可以注释 中心的url地址
    centerUrl: https://verification.kasitesoft.com,http://verification2.kasitesoft.com
    #配置中心申请的appId（必须）
    appId: KASTIE-CLIENT-CRAWLER.MICRO
    #配置中心申请的密码（必须）
    appSecret: Xv1m6XyDtz1D0KIEUo4GI
    #组织机构代码（必须）
    orgCode: 43
    #本地保存配置文件的目录（必须）
    configPath: /Users/daiyanshui/Desktop/Config
    #中心获取的配置 公钥 （必须）
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhEJRYdtg9ipmUJ5d/JNBJdGctLquG2zTxTSA7qz7g+b/RXSsPYPj18GVtjMhsGymKEBm75raxAlw21A5qV+UGX/5uEmqn2hZCBfwzlScNofxs/uErXUOTrwLGRHdMVShuGH8k1KTx95M1b8RiUCZCOh3K0nk11slWiYdEDIFDdp4eDUP3YAmxHhuBiH80Nyf/D/EqhcK9POCD2HVRkP0O2SPTmZeBBtMROrAVUa8rzHAyOzG9tormbdNK5a4c/tjjISfvv7gqfCw9U7mlgEjo3tevEnJH3jVmgroPDVE8Pb9yuWyZ1ip5mYYeY7zzCG/XEYQHRedhUkfnOU7zmLozQIDAQAB
    logfilezip:
        - dirs: D:\wxEventLog
          url: https://wechatcenter.kasitesoft.com/api/weixin/scan/wx53cf738a20d74bb5/upload.do
          isupdate: false