#卡斯特配置中心连接配置。默认是不开启，读取本地配置文件 数据采集子系统
kasite:
     #是否开启中心连接
    isConnectionKastieCenter: true
    #配置中心地址 如果不开启连接中心的时候可以注释 中心的url地址
    centerUrl:  https://verification.kasitesoft.com,http://verification2.kasitesoft.com
    #配置中心申请的appId（必须）:龙岩市第一医院
    appId: KASTIE-CLIENT-CRAWLER.MICRO.21095
    #配置中心申请的密码（必须）
    appSecret: 213e2fc53a
    #组织机构代码（必须）
    orgCode: 21095
    #本地保存配置文件的目录（必须）
    configPath: /Users/daiyanshui/Desktop/Config
    #中心获取的配置 公钥 （必须）
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtJYPqHhNHAwqO4J8HER6bHCxjcTQAM6lz4/+IV1CaK5FA9BruV6bWvivzwU3+/gHalyNAwrIYG0KxQNtfpqzrZC6jKIPUgl33oaHIR/sl6jIzEyMQMhz1sbQaNoAT/tUY3IPWcqZ0RB6flnXbua/c2O5qfUinbGINc1pekLTVjPWABQ02TeMpTfkkCYZSCyl6Jcvc+mOOYvyX5TaQY6Ty1fWKjAVtqhFxaZIcZ2WsybcCkApOikRRfyKMyYU1auzs62evDr7X82ZYMPoc+/zETUG4Fiot/gZ5ohccNI28rqaR6WIPFtfmaEzkGKKsMmPnEpW8tDzA3yZRhukDO0GpQIDAQAB
    logfilezip:
        - dirs: E:\wxEventLog
          url: https://wechatcenter.kasitesoft.com/api/weixin/scan/wx53cf738a20d74bb5/upload.do
          isupdate: true