#卡斯特配置中心连接配置。默认是不开启，读取本地配置文件 数据采集子系统
kasite:
    #系统日志模块配置信息
    log:
        #是否启用ES保存日志
        esLog: true
        #es库地址
        esUrl: 127.0.0.1:9200
    appConfig:
        isConnectionKastieCenter: true
        centerUrl: https://verification.kasitesoft.com,http://verification2.kasitesoft.com
        appId: KASTIE-CLIENT-CRAWLER.MICRO.59
        appSecret: 556f529ee4
        orgCode: 59
        orgName: 福建医科大学附属第二医院(守护程序)
        configPath: /Users/daiyanshui/Desktop/Config
        publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqAxebq2faqMocfEWSbOF2R0gvccPAmUb8px0ybHlP0vLDTGdBT8bneMAH+k/Bi42ZbdMbIAxbtqiGCQlkoQHyX93LNPulgWjlZCGL2AZ6mE1KnuMps9ZhBaqlOmCHx0uiSLRV5Omo/NUUCNyowHrxsI4nQGPCBa0gsIbwcOcF4xXl6WneLtxlmNR0dKlJ0c49QsYfBs43t7nPez0T1eQXrjz/obWRfnck8qK8iJXfnK7FjMOcTawlvAJ7qlf9yH+4D9zWdVRIsBZbdjKg3tnkjw3uog6CwjXu+JpaWSvVcifqg+CtfGLhefMjZbXocefJHCGww5QvqK0ywWk8sB/swIDAQAB
        privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJUtQjAcWlNfWpEGAJwlQ8yarb8r0CqIKjIlGg8XSde1elVYv/+Qqt4caSwsNewek8WodyN9dZVlX8mwZ9dKFsENmYc2LT1C0OQmmBA7L6y0wIFPDjB1JsBGGOEPybnZProrH1KX/o+gywEVHA6Jc0kkOk4Su6mMchQHxlpnB2lFAgMBAAECgYBsIlyCJ2tKWCp8SY+ToGefHtinZQkGa6G6q65SFh2O4ZwF1cmHZcSWMJ4ESR/lQtz3QIDsFvtvCgb/WoJLSwdmVBGxCrV37APIyNv4HTEQNqxHgtCw9OIhVCqY/S21+HdPd/EevJI4L5kzizk/iIZuZScrfU/Yz4gKIjaTCn7bGQJBAPCUvRkFCjdCfIF2CxrQBlSMlBSO13hviCk7UjNtkB8Tg7pYm2ZfOmQwPa9XwhRJcg4gS3NskWFSPZedvDVO91cCQQCevNUVVGqbO92lNw15C5aDOjK/slDoAY/UdkfvSBxJX9yMeLFobpp5EfJJ2/6XQM1gwqIFK+epcaFr++JbT87DAkBhTSb12Y36L4+/pIh1PbFxvLGfZu5KrYE6e92RIzzo9LGQSon/a4BoSQKJykqafeH9SJ57fmuGGwcCLS+Tt+5dAkBnnOaRp6p2bVs97nNy4Wd7fM+HZUN+TRavHg3SWIVuN45kepuCiT93a4l1QI4r+HaWhDTxnzj112AAdkfIRo21AkEAogyby6Zd4z/oav2/nj2QxK/toSecHJAdzkM4WB9s8PSNRtV9Dyic48js+HUiWhrXUX5wJITdKIDQejrzqZg0rQ==
    logfilezip:
        - dirs: E:\wxEventLog
          url: https://wechatcenter.kasitesoft.com/api/weixin/scan/wx53cf738a20d74bb5/upload.do
          isupdate: false