#卡斯特配置中心连接配置。默认是不开启，读取本地配置文件 数据采集子系统
kasite:
     #是否开启中心连接
    isConnectionKastieCenter: true
    #配置中心地址 如果不开启连接中心的时候可以注释 中心的url地址
    centerUrl:  https://verification.kasitesoft.com,http://verification2.kasitesoft.com
    #配置中心申请的appId（必须）:福建医科大学附属口腔医院
    appId: KASTIE-CLIENT-CRAWLER.MICRO.44
    #配置中心申请的密码（必须）
    appSecret: a653057ece
    #组织机构代码（必须）
    orgCode: 44
    #本地保存配置文件的目录（必须）
    configPath: /Users/daiyanshui/Desktop/Config
    #中心获取的配置 公钥 （必须）
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmDAs9kAmltY8ipsbovdAf9xq9gZEqbTSUzlxGV51v4jhAI/81DJj0gsoc3wH/zSg4KQnNYBFcMKOw9L8+U0YZTwiTYT4al/8stfWSBpodZUV6VUOQPIw2pPng+x4xy9jF6kwqS4EC5TzY68xAbnS14jIkrKjq3THf0dOz+NuJmoSIHVVhXq7/eQanUHY41kwq4BBFgGuJdgcBNXxyPYVC8BTj+YecRRJ/yXGvbezw5j/44+YaFCZ5+mTVtBD8JwgmXAL321njbDiddOUtkauBcqZiEwYjM5S4kidAWu3t2B5yOkMTt2ip3BKzC1bTZskgpVahdYAgBvJ8hHLIUk9fQIDAQAB
    logfilezip:
        - dirs: E:\wxEventLog
          url: https://wechatcenter.kasitesoft.com/api/weixin/scan/wx53cf738a20d74bb5/upload.do
          isupdate: true